export const DEFAULT_AUDIT_EVENTS_LIMIT = 100;
export const MAX_AUDIT_EVENTS_LIMIT = 1000;

// Document access audit event types (CMMC AU-2 / NIST 800-171 §3.3.1)
export const DOCUMENT_DOWNLOAD = 'DOCUMENT_DOWNLOAD';
export const DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD';
export const DOCUMENT_ACL_CHANGE = 'DOCUMENT_ACL_CHANGE';
export const DOCUMENT_DELETE = 'DOCUMENT_DELETE';
export const DOCUMENT_ACCESS_DENIED = 'DOCUMENT_ACCESS_DENIED';
