-- Migration: Convert serial() columns to identity columns for INTEGER ID tables only
-- This fixes Drizzle drift issues that cause deployment failures
--
-- Strategy: DROP DEFAULT, ADD IDENTITY, restart sequence from MAX(id)+1
-- Safe because: Column type stays INTEGER, data preserved, FKs remain valid

-- Convert audit_events
DO $$
BEGIN
  ALTER TABLE audit_events ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('audit_events_id_seq', COALESCE((SELECT MAX(id) FROM audit_events), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping audit_events: %', SQLERRM;
END$$;

-- Convert capabilities
DO $$
BEGIN
  ALTER TABLE capabilities ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE capabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('capabilities_id_seq', COALESCE((SELECT MAX(id) FROM capabilities), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping capabilities: %', SQLERRM;
END$$;

-- Convert checklist_items
DO $$
BEGIN
  ALTER TABLE checklist_items ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE checklist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('checklist_items_id_seq', COALESCE((SELECT MAX(id) FROM checklist_items), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping checklist_items: %', SQLERRM;
END$$;

-- Convert checklist_metadata
DO $$
BEGIN
  ALTER TABLE checklist_metadata ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE checklist_metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('checklist_metadata_id_seq', COALESCE((SELECT MAX(id) FROM checklist_metadata), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping checklist_metadata: %', SQLERRM;
END$$;

-- Convert communication_logs
DO $$
BEGIN
  ALTER TABLE communication_logs ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE communication_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('communication_logs_id_seq', COALESCE((SELECT MAX(id) FROM communication_logs), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping communication_logs: %', SQLERRM;
END$$;

-- Convert customer_addresses
DO $$
BEGIN
  ALTER TABLE customer_addresses ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE customer_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('customer_addresses_id_seq', COALESCE((SELECT MAX(id) FROM customer_addresses), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping customer_addresses: %', SQLERRM;
END$$;

-- Convert customer_communications
DO $$
BEGIN
  ALTER TABLE customer_communications ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE customer_communications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('customer_communications_id_seq', COALESCE((SELECT MAX(id) FROM customer_communications), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping customer_communications: %', SQLERRM;
END$$;

-- Convert customer_satisfaction_responses
DO $$
BEGIN
  ALTER TABLE customer_satisfaction_responses ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE customer_satisfaction_responses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('customer_satisfaction_responses_id_seq', COALESCE((SELECT MAX(id) FROM customer_satisfaction_responses), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping customer_satisfaction_responses: %', SQLERRM;
END$$;

-- Convert customer_satisfaction_surveys
DO $$
BEGIN
  ALTER TABLE customer_satisfaction_surveys ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE customer_satisfaction_surveys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('customer_satisfaction_surveys_id_seq', COALESCE((SELECT MAX(id) FROM customer_satisfaction_surveys), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping customer_satisfaction_surveys: %', SQLERRM;
END$$;

-- Convert customer_stock_model_prices
DO $$
BEGIN
  ALTER TABLE customer_stock_model_prices ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE customer_stock_model_prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('customer_stock_model_prices_id_seq', COALESCE((SELECT MAX(id) FROM customer_stock_model_prices), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping customer_stock_model_prices: %', SQLERRM;
END$$;

-- Convert customers
DO $$
BEGIN
  ALTER TABLE customers ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('customers_id_seq', COALESCE((SELECT MAX(id) FROM customers), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping customers: %', SQLERRM;
END$$;

-- Convert daily_task_notifications
DO $$
BEGIN
  ALTER TABLE daily_task_notifications ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE daily_task_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('daily_task_notifications_id_seq', COALESCE((SELECT MAX(id) FROM daily_task_notifications), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping daily_task_notifications: %', SQLERRM;
END$$;

-- Convert daily_tasks
DO $$
BEGIN
  ALTER TABLE daily_tasks ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE daily_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('daily_tasks_id_seq', COALESCE((SELECT MAX(id) FROM daily_tasks), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping daily_tasks: %', SQLERRM;
END$$;

-- Convert departments
DO $$
BEGIN
  ALTER TABLE departments ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('departments_id_seq', COALESCE((SELECT MAX(id) FROM departments), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping departments: %', SQLERRM;
END$$;

-- Convert employee_capabilities
DO $$
BEGIN
  ALTER TABLE employee_capabilities ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE employee_capabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('employee_capabilities_id_seq', COALESCE((SELECT MAX(id) FROM employee_capabilities), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping employee_capabilities: %', SQLERRM;
END$$;

-- Convert employee_certifications
DO $$
BEGIN
  ALTER TABLE employee_certifications ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE employee_certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('employee_certifications_id_seq', COALESCE((SELECT MAX(id) FROM employee_certifications), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping employee_certifications: %', SQLERRM;
END$$;

-- Convert employee_documents
DO $$
BEGIN
  ALTER TABLE employee_documents ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE employee_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('employee_documents_id_seq', COALESCE((SELECT MAX(id) FROM employee_documents), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping employee_documents: %', SQLERRM;
END$$;

-- Convert employee_quiz_attempts
DO $$
BEGIN
  ALTER TABLE employee_quiz_attempts ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE employee_quiz_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('employee_quiz_attempts_id_seq', COALESCE((SELECT MAX(id) FROM employee_quiz_attempts), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping employee_quiz_attempts: %', SQLERRM;
END$$;

-- Convert employee_training_records
DO $$
BEGIN
  ALTER TABLE employee_training_records ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE employee_training_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('employee_training_records_id_seq', COALESCE((SELECT MAX(id) FROM employee_training_records), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping employee_training_records: %', SQLERRM;
END$$;

-- Convert employees
DO $$
BEGIN
  ALTER TABLE employees ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('employees_id_seq', COALESCE((SELECT MAX(id) FROM employees), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping employees: %', SQLERRM;
END$$;

-- Convert enhanced_form_categories
DO $$
BEGIN
  ALTER TABLE enhanced_form_categories ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE enhanced_form_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('enhanced_form_categories_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_form_categories), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping enhanced_form_categories: %', SQLERRM;
END$$;

-- Convert enhanced_form_submissions
DO $$
BEGIN
  ALTER TABLE enhanced_form_submissions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE enhanced_form_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('enhanced_form_submissions_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_form_submissions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping enhanced_form_submissions: %', SQLERRM;
END$$;

-- Convert enhanced_form_versions
DO $$
BEGIN
  ALTER TABLE enhanced_form_versions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE enhanced_form_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('enhanced_form_versions_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_form_versions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping enhanced_form_versions: %', SQLERRM;
END$$;

-- Convert enhanced_forms
DO $$
BEGIN
  ALTER TABLE enhanced_forms ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE enhanced_forms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('enhanced_forms_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_forms), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping enhanced_forms: %', SQLERRM;
END$$;

-- Convert feature_selections
DO $$
BEGIN
  ALTER TABLE feature_selections ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE feature_selections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('feature_selections_id_seq', COALESCE((SELECT MAX(id) FROM feature_selections), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping feature_selections: %', SQLERRM;
END$$;

-- Convert internal_messages
DO $$
BEGIN
  ALTER TABLE internal_messages ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE internal_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('internal_messages_id_seq', COALESCE((SELECT MAX(id) FROM internal_messages), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping internal_messages: %', SQLERRM;
END$$;

-- Convert inventory_balances
DO $$
BEGIN
  ALTER TABLE inventory_balances ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE inventory_balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('inventory_balances_id_seq', COALESCE((SELECT MAX(id) FROM inventory_balances), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping inventory_balances: %', SQLERRM;
END$$;

-- Convert inventory_item_cost_history
DO $$
BEGIN
  ALTER TABLE inventory_item_cost_history ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE inventory_item_cost_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('inventory_item_cost_history_id_seq', COALESCE((SELECT MAX(id) FROM inventory_item_cost_history), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping inventory_item_cost_history: %', SQLERRM;
END$$;

-- Convert inventory_item_groups
DO $$
BEGIN
  ALTER TABLE inventory_item_groups ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE inventory_item_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('inventory_item_groups_id_seq', COALESCE((SELECT MAX(id) FROM inventory_item_groups), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping inventory_item_groups: %', SQLERRM;
END$$;

-- Convert inventory_transactions
DO $$
BEGIN
  ALTER TABLE inventory_transactions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE inventory_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('inventory_transactions_id_seq', COALESCE((SELECT MAX(id) FROM inventory_transactions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping inventory_transactions: %', SQLERRM;
END$$;

-- Convert item_groups
DO $$
BEGIN
  ALTER TABLE item_groups ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE item_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('item_groups_id_seq', COALESCE((SELECT MAX(id) FROM item_groups), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping item_groups: %', SQLERRM;
END$$;

-- Convert kickbacks
DO $$
BEGIN
  ALTER TABLE kickbacks ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE kickbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('kickbacks_id_seq', COALESCE((SELECT MAX(id) FROM kickbacks), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping kickbacks: %', SQLERRM;
END$$;

-- Convert layup_schedule
DO $$
BEGIN
  ALTER TABLE layup_schedule ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE layup_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('layup_schedule_id_seq', COALESCE((SELECT MAX(id) FROM layup_schedule), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping layup_schedule: %', SQLERRM;
END$$;

-- Convert magic_link_tokens
DO $$
BEGIN
  ALTER TABLE magic_link_tokens ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE magic_link_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('magic_link_tokens_id_seq', COALESCE((SELECT MAX(id) FROM magic_link_tokens), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping magic_link_tokens: %', SQLERRM;
END$$;

-- Convert manufacturers_certificates
DO $$
BEGIN
  ALTER TABLE manufacturers_certificates ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE manufacturers_certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('manufacturers_certificates_id_seq', COALESCE((SELECT MAX(id) FROM manufacturers_certificates), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping manufacturers_certificates: %', SQLERRM;
END$$;

-- Convert message_attachments
DO $$
BEGIN
  ALTER TABLE message_attachments ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE message_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('message_attachments_id_seq', COALESCE((SELECT MAX(id) FROM message_attachments), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping message_attachments: %', SQLERRM;
END$$;

-- Convert message_recipients
DO $$
BEGIN
  ALTER TABLE message_recipients ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE message_recipients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('message_recipients_id_seq', COALESCE((SELECT MAX(id) FROM message_recipients), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping message_recipients: %', SQLERRM;
END$$;

-- Convert metal_accessories
DO $$
BEGIN
  ALTER TABLE metal_accessories ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE metal_accessories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('metal_accessories_id_seq', COALESCE((SELECT MAX(id) FROM metal_accessories), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping metal_accessories: %', SQLERRM;
END$$;

-- Convert migration_audit
DO $$
BEGIN
  ALTER TABLE migration_audit ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE migration_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('migration_audit_id_seq', COALESCE((SELECT MAX(id) FROM migration_audit), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping migration_audit: %', SQLERRM;
END$$;

-- Convert non_conforming_items
DO $$
BEGIN
  ALTER TABLE non_conforming_items ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE non_conforming_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('non_conforming_items_id_seq', COALESCE((SELECT MAX(id) FROM non_conforming_items), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping non_conforming_items: %', SQLERRM;
END$$;

-- Convert nonconformance_records
DO $$
BEGIN
  ALTER TABLE nonconformance_records ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE nonconformance_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('nonconformance_records_id_seq', COALESCE((SELECT MAX(id) FROM nonconformance_records), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping nonconformance_records: %', SQLERRM;
END$$;

-- Convert notification_triggers
DO $$
BEGIN
  ALTER TABLE notification_triggers ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE notification_triggers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('notification_triggers_id_seq', COALESCE((SELECT MAX(id) FROM notification_triggers), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping notification_triggers: %', SQLERRM;
END$$;

-- Convert oem_priority_settings
DO $$
BEGIN
  ALTER TABLE oem_priority_settings ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE oem_priority_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('oem_priority_settings_id_seq', COALESCE((SELECT MAX(id) FROM oem_priority_settings), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping oem_priority_settings: %', SQLERRM;
END$$;

-- Convert order_departments
DO $$
BEGIN
  ALTER TABLE order_departments ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE order_departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('order_departments_id_seq', COALESCE((SELECT MAX(id) FROM order_departments), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping order_departments: %', SQLERRM;
END$$;

-- Convert order_id_reservations
DO $$
BEGIN
  ALTER TABLE order_id_reservations ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE order_id_reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('order_id_reservations_id_seq', COALESCE((SELECT MAX(id) FROM order_id_reservations), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping order_id_reservations: %', SQLERRM;
END$$;

-- Convert order_id_sequences
DO $$
BEGIN
  ALTER TABLE order_id_sequences ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE order_id_sequences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('order_id_sequences_id_seq', COALESCE((SELECT MAX(id) FROM order_id_sequences), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping order_id_sequences: %', SQLERRM;
END$$;

-- Convert order_statuses
DO $$
BEGIN
  ALTER TABLE order_statuses ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE order_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('order_statuses_id_seq', COALESCE((SELECT MAX(id) FROM order_statuses), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping order_statuses: %', SQLERRM;
END$$;

-- Convert orders_unified
DO $$
BEGIN
  ALTER TABLE orders_unified ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE orders_unified ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('orders_unified_id_seq', COALESCE((SELECT MAX(id) FROM orders_unified), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping orders_unified: %', SQLERRM;
END$$;

-- Convert p2_customers
DO $$
BEGIN
  ALTER TABLE p2_customers ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE p2_customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('p2_customers_id_seq', COALESCE((SELECT MAX(id) FROM p2_customers), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping p2_customers: %', SQLERRM;
END$$;

-- Convert p2_employee_part_certifications
DO $$
BEGIN
  ALTER TABLE p2_employee_part_certifications ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE p2_employee_part_certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('p2_employee_part_certifications_id_seq', COALESCE((SELECT MAX(id) FROM p2_employee_part_certifications), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping p2_employee_part_certifications: %', SQLERRM;
END$$;

-- Convert p2_part_certifications
DO $$
BEGIN
  ALTER TABLE p2_part_certifications ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE p2_part_certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('p2_part_certifications_id_seq', COALESCE((SELECT MAX(id) FROM p2_part_certifications), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping p2_part_certifications: %', SQLERRM;
END$$;

-- Convert p2_production_orders
DO $$
BEGIN
  ALTER TABLE p2_production_orders ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE p2_production_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('p2_production_orders_id_seq', COALESCE((SELECT MAX(id) FROM p2_production_orders), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping p2_production_orders: %', SQLERRM;
END$$;

-- Convert p2_purchase_order_items
DO $$
BEGIN
  ALTER TABLE p2_purchase_order_items ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE p2_purchase_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('p2_purchase_order_items_id_seq', COALESCE((SELECT MAX(id) FROM p2_purchase_order_items), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping p2_purchase_order_items: %', SQLERRM;
END$$;

-- Convert p2_purchase_orders
DO $$
BEGIN
  ALTER TABLE p2_purchase_orders ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE p2_purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('p2_purchase_orders_id_seq', COALESCE((SELECT MAX(id) FROM p2_purchase_orders), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping p2_purchase_orders: %', SQLERRM;
END$$;

-- Convert parts_requests
DO $$
BEGIN
  ALTER TABLE parts_requests ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE parts_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('parts_requests_id_seq', COALESCE((SELECT MAX(id) FROM parts_requests), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping parts_requests: %', SQLERRM;
END$$;

-- Convert payments
DO $$
BEGIN
  ALTER TABLE payments ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('payments_id_seq', COALESCE((SELECT MAX(id) FROM payments), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping payments: %', SQLERRM;
END$$;

-- Convert pdf_documents
DO $$
BEGIN
  ALTER TABLE pdf_documents ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE pdf_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('pdf_documents_id_seq', COALESCE((SELECT MAX(id) FROM pdf_documents), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping pdf_documents: %', SQLERRM;
END$$;

-- Convert po_product_selections
DO $$
BEGIN
  ALTER TABLE po_product_selections ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE po_product_selections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('po_product_selections_id_seq', COALESCE((SELECT MAX(id) FROM po_product_selections), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping po_product_selections: %', SQLERRM;
END$$;

-- Convert po_products
DO $$
BEGIN
  ALTER TABLE po_products ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE po_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('po_products_id_seq', COALESCE((SELECT MAX(id) FROM po_products), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping po_products: %', SQLERRM;
END$$;

-- Convert production_orders
DO $$
BEGIN
  ALTER TABLE production_orders ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE production_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('production_orders_id_seq', COALESCE((SELECT MAX(id) FROM production_orders), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping production_orders: %', SQLERRM;
END$$;

-- Convert production_queue
DO $$
BEGIN
  ALTER TABLE production_queue ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE production_queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('production_queue_id_seq', COALESCE((SELECT MAX(id) FROM production_queue), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping production_queue: %', SQLERRM;
END$$;

-- Convert purchase_order_items
DO $$
BEGIN
  ALTER TABLE purchase_order_items ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE purchase_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('purchase_order_items_id_seq', COALESCE((SELECT MAX(id) FROM purchase_order_items), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping purchase_order_items: %', SQLERRM;
END$$;

-- Convert purchase_orders
DO $$
BEGIN
  ALTER TABLE purchase_orders ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('purchase_orders_id_seq', COALESCE((SELECT MAX(id) FROM purchase_orders), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping purchase_orders: %', SQLERRM;
END$$;

-- Convert purchase_review_checklists
DO $$
BEGIN
  ALTER TABLE purchase_review_checklists ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE purchase_review_checklists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('purchase_review_checklists_id_seq', COALESCE((SELECT MAX(id) FROM purchase_review_checklists), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping purchase_review_checklists: %', SQLERRM;
END$$;

-- Convert qc_definitions
DO $$
BEGIN
  ALTER TABLE qc_definitions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE qc_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('qc_definitions_id_seq', COALESCE((SELECT MAX(id) FROM qc_definitions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping qc_definitions: %', SQLERRM;
END$$;

-- Convert qc_submissions
DO $$
BEGIN
  ALTER TABLE qc_submissions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE qc_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('qc_submissions_id_seq', COALESCE((SELECT MAX(id) FROM qc_submissions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping qc_submissions: %', SQLERRM;
END$$;

-- Convert refund_requests
DO $$
BEGIN
  ALTER TABLE refund_requests ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE refund_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('refund_requests_id_seq', COALESCE((SELECT MAX(id) FROM refund_requests), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping refund_requests: %', SQLERRM;
END$$;

-- Convert rfq_risk_assessments
DO $$
BEGIN
  ALTER TABLE rfq_risk_assessments ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE rfq_risk_assessments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('rfq_risk_assessments_id_seq', COALESCE((SELECT MAX(id) FROM rfq_risk_assessments), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping rfq_risk_assessments: %', SQLERRM;
END$$;

-- Convert sessions
DO $$
BEGIN
  ALTER TABLE sessions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('sessions_id_seq', COALESCE((SELECT MAX(id) FROM sessions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping sessions: %', SQLERRM;
END$$;

-- Convert task_items
DO $$
BEGIN
  ALTER TABLE task_items ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE task_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('task_items_id_seq', COALESCE((SELECT MAX(id) FROM task_items), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping task_items: %', SQLERRM;
END$$;

-- Convert task_templates
DO $$
BEGIN
  ALTER TABLE task_templates ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE task_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('task_templates_id_seq', COALESCE((SELECT MAX(id) FROM task_templates), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping task_templates: %', SQLERRM;
END$$;

-- Convert time_clock_entries
DO $$
BEGIN
  ALTER TABLE time_clock_entries ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE time_clock_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('time_clock_entries_id_seq', COALESCE((SELECT MAX(id) FROM time_clock_entries), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping time_clock_entries: %', SQLERRM;
END$$;

-- Convert training_attendees
DO $$
BEGIN
  ALTER TABLE training_attendees ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_attendees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_attendees_id_seq', COALESCE((SELECT MAX(id) FROM training_attendees), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_attendees: %', SQLERRM;
END$$;

-- Convert training_completions
DO $$
BEGIN
  ALTER TABLE training_completions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_completions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_completions_id_seq', COALESCE((SELECT MAX(id) FROM training_completions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_completions: %', SQLERRM;
END$$;

-- Convert training_matrix
DO $$
BEGIN
  ALTER TABLE training_matrix ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_matrix ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_matrix_id_seq', COALESCE((SELECT MAX(id) FROM training_matrix), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_matrix: %', SQLERRM;
END$$;

-- Convert training_modules
DO $$
BEGIN
  ALTER TABLE training_modules ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_modules_id_seq', COALESCE((SELECT MAX(id) FROM training_modules), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_modules: %', SQLERRM;
END$$;

-- Convert training_question_options
DO $$
BEGIN
  ALTER TABLE training_question_options ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_question_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_question_options_id_seq', COALESCE((SELECT MAX(id) FROM training_question_options), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_question_options: %', SQLERRM;
END$$;

-- Convert training_questions
DO $$
BEGIN
  ALTER TABLE training_questions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_questions_id_seq', COALESCE((SELECT MAX(id) FROM training_questions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_questions: %', SQLERRM;
END$$;

-- Convert training_quiz_answers
DO $$
BEGIN
  ALTER TABLE training_quiz_answers ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_quiz_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_quiz_answers_id_seq', COALESCE((SELECT MAX(id) FROM training_quiz_answers), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_quiz_answers: %', SQLERRM;
END$$;

-- Convert training_quiz_questions
DO $$
BEGIN
  ALTER TABLE training_quiz_questions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_quiz_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_quiz_questions_id_seq', COALESCE((SELECT MAX(id) FROM training_quiz_questions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_quiz_questions: %', SQLERRM;
END$$;

-- Convert training_sessions
DO $$
BEGIN
  ALTER TABLE training_sessions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE training_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('training_sessions_id_seq', COALESCE((SELECT MAX(id) FROM training_sessions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping training_sessions: %', SQLERRM;
END$$;

-- Convert user_capabilities
DO $$
BEGIN
  ALTER TABLE user_capabilities ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE user_capabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('user_capabilities_id_seq', COALESCE((SELECT MAX(id) FROM user_capabilities), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping user_capabilities: %', SQLERRM;
END$$;

-- Convert user_integrations
DO $$
BEGIN
  ALTER TABLE user_integrations ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE user_integrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('user_integrations_id_seq', COALESCE((SELECT MAX(id) FROM user_integrations), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping user_integrations: %', SQLERRM;
END$$;

-- Convert user_sessions
DO $$
BEGIN
  ALTER TABLE user_sessions ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE user_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('user_sessions_id_seq', COALESCE((SELECT MAX(id) FROM user_sessions), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping user_sessions: %', SQLERRM;
END$$;

-- Convert users
DO $$
BEGIN
  ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping users: %', SQLERRM;
END$$;

-- Convert vendor_contacts
DO $$
BEGIN
  ALTER TABLE vendor_contacts ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_contacts_id_seq', COALESCE((SELECT MAX(id) FROM vendor_contacts), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_contacts: %', SQLERRM;
END$$;

-- Convert vendor_evaluations
DO $$
BEGIN
  ALTER TABLE vendor_evaluations ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_evaluations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_evaluations_id_seq', COALESCE((SELECT MAX(id) FROM vendor_evaluations), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_evaluations: %', SQLERRM;
END$$;

-- Convert vendor_monthly_evaluations
DO $$
BEGIN
  ALTER TABLE vendor_monthly_evaluations ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_monthly_evaluations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_monthly_evaluations_id_seq', COALESCE((SELECT MAX(id) FROM vendor_monthly_evaluations), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_monthly_evaluations: %', SQLERRM;
END$$;

-- Convert vendor_parts
DO $$
BEGIN
  ALTER TABLE vendor_parts ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_parts_id_seq', COALESCE((SELECT MAX(id) FROM vendor_parts), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_parts: %', SQLERRM;
END$$;

-- Convert vendor_po_items
DO $$
BEGIN
  ALTER TABLE vendor_po_items ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_po_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_po_items_id_seq', COALESCE((SELECT MAX(id) FROM vendor_po_items), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_po_items: %', SQLERRM;
END$$;

-- Convert vendor_po_settings
DO $$
BEGIN
  ALTER TABLE vendor_po_settings ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_po_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_po_settings_id_seq', COALESCE((SELECT MAX(id) FROM vendor_po_settings), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_po_settings: %', SQLERRM;
END$$;

-- Convert vendor_pos
DO $$
BEGIN
  ALTER TABLE vendor_pos ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_pos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_pos_id_seq', COALESCE((SELECT MAX(id) FROM vendor_pos), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_pos: %', SQLERRM;
END$$;

-- Convert vendor_scope_groups
DO $$
BEGIN
  ALTER TABLE vendor_scope_groups ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_scope_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_scope_groups_id_seq', COALESCE((SELECT MAX(id) FROM vendor_scope_groups), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_scope_groups: %', SQLERRM;
END$$;

-- Convert vendor_scope_items
DO $$
BEGIN
  ALTER TABLE vendor_scope_items ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendor_scope_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendor_scope_items_id_seq', COALESCE((SELECT MAX(id) FROM vendor_scope_items), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendor_scope_items: %', SQLERRM;
END$$;

-- Convert vendors
DO $$
BEGIN
  ALTER TABLE vendors ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE vendors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('vendors_id_seq', COALESCE((SELECT MAX(id) FROM vendors), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping vendors: %', SQLERRM;
END$$;

-- Convert weekly_schedule_assignments
DO $$
BEGIN
  ALTER TABLE weekly_schedule_assignments ALTER COLUMN id DROP DEFAULT;
  ALTER TABLE weekly_schedule_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval('weekly_schedule_assignments_id_seq', COALESCE((SELECT MAX(id) FROM weekly_schedule_assignments), 0) + 1, false);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping weekly_schedule_assignments: %', SQLERRM;
END$$;

