-- Migration: Convert ONLY p2_customers to identity column
-- This fixes the deployment drift issue for p2_customers table specifically

DO $$
BEGIN
  -- Check if p2_customers still uses serial/sequence
  IF EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'p2_customers'::regclass
    AND attname = 'id'
    AND attidentity = ''
  ) THEN
    -- Drop the default (sequence-based)
    ALTER TABLE p2_customers ALTER COLUMN id DROP DEFAULT;
    
    -- Add identity
    ALTER TABLE p2_customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    
    -- Restart the sequence from current MAX + 1
    PERFORM setval('p2_customers_id_seq', COALESCE((SELECT MAX(id) FROM p2_customers), 0) + 1, false);
    
    RAISE NOTICE 'Converted p2_customers to identity column';
  ELSE
    RAISE NOTICE 'p2_customers already uses identity, skipping';
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Error converting p2_customers: %', SQLERRM;
END$$;
