-- Migration: Convert all serial() columns to identity columns
-- This fixes Drizzle drift issues where serial creates sequences that appear as drift
-- and cause invalid "ALTER TABLE ... SET DATA TYPE serial" statements during deployment
--
-- Strategy for each table:
-- 1. Drop the existing DEFAULT nextval(...) 
-- 2. Add GENERATED BY DEFAULT AS IDENTITY using existing sequence
-- 3. Set sequence to continue from MAX(id) + 1
--
-- This migration is safe because:
-- - Column type stays INTEGER (no data type change)
-- - Existing data is preserved
-- - Foreign key references remain valid
-- - Sequences are reused, not recreated

-- Convert order_department_types
ALTER TABLE order_department_types 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE order_department_types 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_department_types_id_seq RESTART WITH 1);

SELECT setval('order_department_types_id_seq', COALESCE((SELECT MAX(id) FROM order_department_types), 0) + 1, false);

-- Convert order_status_types
ALTER TABLE order_status_types 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE order_status_types 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_status_types_id_seq RESTART WITH 1);

SELECT setval('order_status_types_id_seq', COALESCE((SELECT MAX(id) FROM order_status_types), 0) + 1, false);

-- Convert all_orders
ALTER TABLE all_orders 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE all_orders 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME all_orders_id_seq RESTART WITH 1);

SELECT setval('all_orders_id_seq', COALESCE((SELECT MAX(id) FROM all_orders), 0) + 1, false);

-- Convert orders (legacy)
ALTER TABLE orders 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE orders 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME orders_id_seq RESTART WITH 1);

SELECT setval('orders_id_seq', COALESCE((SELECT MAX(id) FROM orders), 0) + 1, false);

-- Convert linked_order_groups
ALTER TABLE linked_order_groups 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE linked_order_groups 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME linked_order_groups_id_seq RESTART WITH 1);

SELECT setval('linked_order_groups_id_seq', COALESCE((SELECT MAX(id) FROM linked_order_groups), 0) + 1, false);

-- Convert linked_orders
ALTER TABLE linked_orders 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE linked_orders 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME linked_orders_id_seq RESTART WITH 1);

SELECT setval('linked_orders_id_seq', COALESCE((SELECT MAX(id) FROM linked_orders), 0) + 1, false);

-- Convert followup_orders
ALTER TABLE followup_orders 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE followup_orders 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME followup_orders_id_seq RESTART WITH 1);

SELECT setval('followup_orders_id_seq', COALESCE((SELECT MAX(id) FROM followup_orders), 0) + 1, false);

-- Convert order_filter_presets
ALTER TABLE order_filter_presets 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE order_filter_presets 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_filter_presets_id_seq RESTART WITH 1);

SELECT setval('order_filter_presets_id_seq', COALESCE((SELECT MAX(id) FROM order_filter_presets), 0) + 1, false);

-- Convert csv_data
ALTER TABLE csv_data 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE csv_data 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME csv_data_id_seq RESTART WITH 1);

SELECT setval('csv_data_id_seq', COALESCE((SELECT MAX(id) FROM csv_data), 0) + 1, false);

-- Convert customer_types
ALTER TABLE customer_types 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE customer_types 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME customer_types_id_seq RESTART WITH 1);

SELECT setval('customer_types_id_seq', COALESCE((SELECT MAX(id) FROM customer_types), 0) + 1, false);

-- Convert persistent_discounts
ALTER TABLE persistent_discounts 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE persistent_discounts 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME persistent_discounts_id_seq RESTART WITH 1);

SELECT setval('persistent_discounts_id_seq', COALESCE((SELECT MAX(id) FROM persistent_discounts), 0) + 1, false);

-- Convert short_term_sales
ALTER TABLE short_term_sales 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE short_term_sales 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME short_term_sales_id_seq RESTART WITH 1);

SELECT setval('short_term_sales_id_seq', COALESCE((SELECT MAX(id) FROM short_term_sales), 0) + 1, false);

-- Convert feature_categories
ALTER TABLE feature_categories 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE feature_categories 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME feature_categories_id_seq RESTART WITH 1);

SELECT setval('feature_categories_id_seq', COALESCE((SELECT MAX(id) FROM feature_categories), 0) + 1, false);

-- Convert feature_sub_categories
ALTER TABLE feature_sub_categories 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE feature_sub_categories 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME feature_sub_categories_id_seq RESTART WITH 1);

SELECT setval('feature_sub_categories_id_seq', COALESCE((SELECT MAX(id) FROM feature_sub_categories), 0) + 1, false);

-- Convert features
ALTER TABLE features 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE features 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME features_id_seq RESTART WITH 1);

SELECT setval('features_id_seq', COALESCE((SELECT MAX(id) FROM features), 0) + 1, false);

-- Convert stock_models
ALTER TABLE stock_models 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE stock_models 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME stock_models_id_seq RESTART WITH 1);

SELECT setval('stock_models_id_seq', COALESCE((SELECT MAX(id) FROM stock_models), 0) + 1, false);

-- Convert customer_stock_model_prices
ALTER TABLE customer_stock_model_prices 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE customer_stock_model_prices 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME customer_stock_model_prices_id_seq RESTART WITH 1);

SELECT setval('customer_stock_model_prices_id_seq', COALESCE((SELECT MAX(id) FROM customer_stock_model_prices), 0) + 1, false);

-- Convert payments
ALTER TABLE payments 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE payments 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME payments_id_seq RESTART WITH 1);

SELECT setval('payments_id_seq', COALESCE((SELECT MAX(id) FROM payments), 0) + 1, false);

-- Convert credit_card_transactions
ALTER TABLE credit_card_transactions 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE credit_card_transactions 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME credit_card_transactions_id_seq RESTART WITH 1);

SELECT setval('credit_card_transactions_id_seq', COALESCE((SELECT MAX(id) FROM credit_card_transactions), 0) + 1, false);

-- Convert refund_requests
ALTER TABLE refund_requests 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE refund_requests 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME refund_requests_id_seq RESTART WITH 1);

SELECT setval('refund_requests_id_seq', COALESCE((SELECT MAX(id) FROM refund_requests), 0) + 1, false);

-- Convert forms
ALTER TABLE forms 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE forms 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME forms_id_seq RESTART WITH 1);

SELECT setval('forms_id_seq', COALESCE((SELECT MAX(id) FROM forms), 0) + 1, false);

-- Convert form_submissions
ALTER TABLE form_submissions 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE form_submissions 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME form_submissions_id_seq RESTART WITH 1);

SELECT setval('form_submissions_id_seq', COALESCE((SELECT MAX(id) FROM form_submissions), 0) + 1, false);

-- Convert inventory_items
ALTER TABLE inventory_items 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE inventory_items 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME inventory_items_id_seq RESTART WITH 1);

SELECT setval('inventory_items_id_seq', COALESCE((SELECT MAX(id) FROM inventory_items), 0) + 1, false);

-- Convert inventory_item_cost_history
ALTER TABLE inventory_item_cost_history 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE inventory_item_cost_history 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME inventory_item_cost_history_id_seq RESTART WITH 1);

SELECT setval('inventory_item_cost_history_id_seq', COALESCE((SELECT MAX(id) FROM inventory_item_cost_history), 0) + 1, false);

-- Convert item_groups
ALTER TABLE item_groups 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE item_groups 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME item_groups_id_seq RESTART WITH 1);

SELECT setval('item_groups_id_seq', COALESCE((SELECT MAX(id) FROM item_groups), 0) + 1, false);

-- Convert inventory_item_groups
ALTER TABLE inventory_item_groups 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE inventory_item_groups 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME inventory_item_groups_id_seq RESTART WITH 1);

SELECT setval('inventory_item_groups_id_seq', COALESCE((SELECT MAX(id) FROM inventory_item_groups), 0) + 1, false);

-- Convert vendor_scope_items
ALTER TABLE vendor_scope_items 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE vendor_scope_items 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendor_scope_items_id_seq RESTART WITH 1);

SELECT setval('vendor_scope_items_id_seq', COALESCE((SELECT MAX(id) FROM vendor_scope_items), 0) + 1, false);

-- Convert vendor_scope_groups
ALTER TABLE vendor_scope_groups 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE vendor_scope_groups 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendor_scope_groups_id_seq RESTART WITH 1);

SELECT setval('vendor_scope_groups_id_seq', COALESCE((SELECT MAX(id) FROM vendor_scope_groups), 0) + 1, false);

-- Convert inventory_scans
ALTER TABLE inventory_scans 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE inventory_scans 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME inventory_scans_id_seq RESTART WITH 1);

SELECT setval('inventory_scans_id_seq', COALESCE((SELECT MAX(id) FROM inventory_scans), 0) + 1, false);

-- Convert parts_requests
ALTER TABLE parts_requests 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE parts_requests 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME parts_requests_id_seq RESTART WITH 1);

SELECT setval('parts_requests_id_seq', COALESCE((SELECT MAX(id) FROM parts_requests), 0) + 1, false);

-- Convert rts_inventory
ALTER TABLE rts_inventory 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE rts_inventory 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME rts_inventory_id_seq RESTART WITH 1);

SELECT setval('rts_inventory_id_seq', COALESCE((SELECT MAX(id) FROM rts_inventory), 0) + 1, false);

-- Convert rts_inventory_history
ALTER TABLE rts_inventory_history 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE rts_inventory_history 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME rts_inventory_history_id_seq RESTART WITH 1);

SELECT setval('rts_inventory_history_id_seq', COALESCE((SELECT MAX(id) FROM rts_inventory_history), 0) + 1, false);

-- Convert rts_sales
ALTER TABLE rts_sales 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE rts_sales 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME rts_sales_id_seq RESTART WITH 1);

SELECT setval('rts_sales_id_seq', COALESCE((SELECT MAX(id) FROM rts_sales), 0) + 1, false);

-- Convert rts_sale_items
ALTER TABLE rts_sale_items 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE rts_sale_items 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME rts_sale_items_id_seq RESTART WITH 1);

SELECT setval('rts_sale_items_id_seq', COALESCE((SELECT MAX(id) FROM rts_sale_items), 0) + 1, false);

-- Convert employees
ALTER TABLE employees 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE employees 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME employees_id_seq RESTART WITH 1);

SELECT setval('employees_id_seq', COALESCE((SELECT MAX(id) FROM employees), 0) + 1, false);

-- Convert certifications
ALTER TABLE certifications 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE certifications 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME certifications_id_seq RESTART WITH 1);

SELECT setval('certifications_id_seq', COALESCE((SELECT MAX(id) FROM certifications), 0) + 1, false);

-- Convert employee_certifications
ALTER TABLE employee_certifications 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE employee_certifications 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME employee_certifications_id_seq RESTART WITH 1);

SELECT setval('employee_certifications_id_seq', COALESCE((SELECT MAX(id) FROM employee_certifications), 0) + 1, false);

-- Convert evaluations
ALTER TABLE evaluations 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE evaluations 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME evaluations_id_seq RESTART WITH 1);

SELECT setval('evaluations_id_seq', COALESCE((SELECT MAX(id) FROM evaluations), 0) + 1, false);

-- Convert employee_documents
ALTER TABLE employee_documents 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE employee_documents 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME employee_documents_id_seq RESTART WITH 1);

SELECT setval('employee_documents_id_seq', COALESCE((SELECT MAX(id) FROM employee_documents), 0) + 1, false);

-- Convert employee_audit_log
ALTER TABLE employee_audit_log 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE employee_audit_log 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME employee_audit_log_id_seq RESTART WITH 1);

SELECT setval('employee_audit_log_id_seq', COALESCE((SELECT MAX(id) FROM employee_audit_log), 0) + 1, false);

-- Convert training_modules
ALTER TABLE training_modules 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE training_modules 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME training_modules_id_seq RESTART WITH 1);

SELECT setval('training_modules_id_seq', COALESCE((SELECT MAX(id) FROM training_modules), 0) + 1, false);

-- Convert training_questions
ALTER TABLE training_questions 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE training_questions 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME training_questions_id_seq RESTART WITH 1);

SELECT setval('training_questions_id_seq', COALESCE((SELECT MAX(id) FROM training_questions), 0) + 1, false);

-- Convert training_question_options
ALTER TABLE training_question_options 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE training_question_options 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME training_question_options_id_seq RESTART WITH 1);

SELECT setval('training_question_options_id_seq', COALESCE((SELECT MAX(id) FROM training_question_options), 0) + 1, false);

-- Convert employee_training_records
ALTER TABLE employee_training_records 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE employee_training_records 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME employee_training_records_id_seq RESTART WITH 1);

SELECT setval('employee_training_records_id_seq', COALESCE((SELECT MAX(id) FROM employee_training_records), 0) + 1, false);

-- Convert employee_quiz_attempts
ALTER TABLE employee_quiz_attempts 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE employee_quiz_attempts 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME employee_quiz_attempts_id_seq RESTART WITH 1);

SELECT setval('employee_quiz_attempts_id_seq', COALESCE((SELECT MAX(id) FROM employee_quiz_attempts), 0) + 1, false);

-- Convert training_matrix
ALTER TABLE training_matrix 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE training_matrix 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME training_matrix_id_seq RESTART WITH 1);

SELECT setval('training_matrix_id_seq', COALESCE((SELECT MAX(id) FROM training_matrix), 0) + 1, false);

-- Convert users
ALTER TABLE users 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE users 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME users_id_seq RESTART WITH 1);

SELECT setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users), 0) + 1, false);

-- Convert user_sessions
ALTER TABLE user_sessions 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE user_sessions 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME user_sessions_id_seq RESTART WITH 1);

SELECT setval('user_sessions_id_seq', COALESCE((SELECT MAX(id) FROM user_sessions), 0) + 1, false);

-- Convert user_integrations
ALTER TABLE user_integrations 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE user_integrations 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME user_integrations_id_seq RESTART WITH 1);

SELECT setval('user_integrations_id_seq', COALESCE((SELECT MAX(id) FROM user_integrations), 0) + 1, false);

-- Convert capabilities
ALTER TABLE capabilities 
  ALTER COLUMN id DROP DEFAULT;
  
ALTER TABLE capabilities 
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME capabilities_id_seq RESTART WITH 1);

SELECT setval('capabilities_id_seq', COALESCE((SELECT MAX(id) FROM capabilities), 0) + 1, false);

-- Continue with remaining tables...

-- Convert qc_definitions
ALTER TABLE qc_definitions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE qc_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME qc_definitions_id_seq RESTART WITH 1);
SELECT setval('qc_definitions_id_seq', COALESCE((SELECT MAX(id) FROM qc_definitions), 0) + 1, false);

-- Convert qc_submissions
ALTER TABLE qc_submissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE qc_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME qc_submissions_id_seq RESTART WITH 1);
SELECT setval('qc_submissions_id_seq', COALESCE((SELECT MAX(id) FROM qc_submissions), 0) + 1, false);

-- Convert maintenance_schedules
ALTER TABLE maintenance_schedules ALTER COLUMN id DROP DEFAULT;
ALTER TABLE maintenance_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME maintenance_schedules_id_seq RESTART WITH 1);
SELECT setval('maintenance_schedules_id_seq', COALESCE((SELECT MAX(id) FROM maintenance_schedules), 0) + 1, false);

-- Convert maintenance_logs
ALTER TABLE maintenance_logs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE maintenance_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME maintenance_logs_id_seq RESTART WITH 1);
SELECT setval('maintenance_logs_id_seq', COALESCE((SELECT MAX(id) FROM maintenance_logs), 0) + 1, false);

-- Convert time_clock_entries
ALTER TABLE time_clock_entries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE time_clock_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME time_clock_entries_id_seq RESTART WITH 1);
SELECT setval('time_clock_entries_id_seq', COALESCE((SELECT MAX(id) FROM time_clock_entries), 0) + 1, false);

-- Convert checklist_items
ALTER TABLE checklist_items ALTER COLUMN id DROP DEFAULT;
ALTER TABLE checklist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME checklist_items_id_seq RESTART WITH 1);
SELECT setval('checklist_items_id_seq', COALESCE((SELECT MAX(id) FROM checklist_items), 0) + 1, false);

-- Convert onboarding_docs
ALTER TABLE onboarding_docs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE onboarding_docs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME onboarding_docs_id_seq RESTART WITH 1);
SELECT setval('onboarding_docs_id_seq', COALESCE((SELECT MAX(id) FROM onboarding_docs), 0) + 1, false);

-- Convert purchase_review_checklists
ALTER TABLE purchase_review_checklists ALTER COLUMN id DROP DEFAULT;
ALTER TABLE purchase_review_checklists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME purchase_review_checklists_id_seq RESTART WITH 1);
SELECT setval('purchase_review_checklists_id_seq', COALESCE((SELECT MAX(id) FROM purchase_review_checklists), 0) + 1, false);

-- Convert manufacturers_certificates
ALTER TABLE manufacturers_certificates ALTER COLUMN id DROP DEFAULT;
ALTER TABLE manufacturers_certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME manufacturers_certificates_id_seq RESTART WITH 1);
SELECT setval('manufacturers_certificates_id_seq', COALESCE((SELECT MAX(id) FROM manufacturers_certificates), 0) + 1, false);

-- Convert molds
ALTER TABLE molds ALTER COLUMN id DROP DEFAULT;
ALTER TABLE molds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME molds_id_seq RESTART WITH 1);
SELECT setval('molds_id_seq', COALESCE((SELECT MAX(id) FROM molds), 0) + 1, false);

-- Convert employee_layup_settings
ALTER TABLE employee_layup_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE employee_layup_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME employee_layup_settings_id_seq RESTART WITH 1);
SELECT setval('employee_layup_settings_id_seq', COALESCE((SELECT MAX(id) FROM employee_layup_settings), 0) + 1, false);

-- Convert production_queue
ALTER TABLE production_queue ALTER COLUMN id DROP DEFAULT;
ALTER TABLE production_queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME production_queue_id_seq RESTART WITH 1);
SELECT setval('production_queue_id_seq', COALESCE((SELECT MAX(id) FROM production_queue), 0) + 1, false);

-- Convert layup_schedule
ALTER TABLE layup_schedule ALTER COLUMN id DROP DEFAULT;
ALTER TABLE layup_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME layup_schedule_id_seq RESTART WITH 1);
SELECT setval('layup_schedule_id_seq', COALESCE((SELECT MAX(id) FROM layup_schedule), 0) + 1, false);

-- Convert p2_customers (this is the customers table)
ALTER TABLE p2_customers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE p2_customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME p2_customers_id_seq RESTART WITH 1);
SELECT setval('p2_customers_id_seq', COALESCE((SELECT MAX(id) FROM p2_customers), 0) + 1, false);

-- Convert customer_addresses
ALTER TABLE customer_addresses ALTER COLUMN id DROP DEFAULT;
ALTER TABLE customer_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME customer_addresses_id_seq RESTART WITH 1);
SELECT setval('customer_addresses_id_seq', COALESCE((SELECT MAX(id) FROM customer_addresses), 0) + 1, false);

-- Convert vendors
ALTER TABLE vendors ALTER COLUMN id DROP DEFAULT;
ALTER TABLE vendors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendors_id_seq RESTART WITH 1);
SELECT setval('vendors_id_seq', COALESCE((SELECT MAX(id) FROM vendors), 0) + 1, false);

-- Convert vendor_contacts
ALTER TABLE vendor_contacts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE vendor_contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendor_contacts_id_seq RESTART WITH 1);
SELECT setval('vendor_contacts_id_seq', COALESCE((SELECT MAX(id) FROM vendor_contacts), 0) + 1, false);

-- Convert vendor_monthly_evaluations
ALTER TABLE vendor_monthly_evaluations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE vendor_monthly_evaluations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendor_monthly_evaluations_id_seq RESTART WITH 1);
SELECT setval('vendor_monthly_evaluations_id_seq', COALESCE((SELECT MAX(id) FROM vendor_monthly_evaluations), 0) + 1, false);

-- Convert inventory_balances
ALTER TABLE inventory_balances ALTER COLUMN id DROP DEFAULT;
ALTER TABLE inventory_balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME inventory_balances_id_seq RESTART WITH 1);
SELECT setval('inventory_balances_id_seq', COALESCE((SELECT MAX(id) FROM inventory_balances), 0) + 1, false);

-- Convert inventory_transactions
ALTER TABLE inventory_transactions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE inventory_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME inventory_transactions_id_seq RESTART WITH 1);
SELECT setval('inventory_transactions_id_seq', COALESCE((SELECT MAX(id) FROM inventory_transactions), 0) + 1, false);

-- Convert vendor_parts
ALTER TABLE vendor_parts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE vendor_parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendor_parts_id_seq RESTART WITH 1);
SELECT setval('vendor_parts_id_seq', COALESCE((SELECT MAX(id) FROM vendor_parts), 0) + 1, false);

-- Convert vendor_pos
ALTER TABLE vendor_pos ALTER COLUMN id DROP DEFAULT;
ALTER TABLE vendor_pos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendor_pos_id_seq RESTART WITH 1);
SELECT setval('vendor_pos_id_seq', COALESCE((SELECT MAX(id) FROM vendor_pos), 0) + 1, false);

-- Convert vendor_po_items (this is p2_purchase_order_items)
ALTER TABLE p2_purchase_order_items ALTER COLUMN id DROP DEFAULT;
ALTER TABLE p2_purchase_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME p2_purchase_order_items_id_seq RESTART WITH 1);
SELECT setval('p2_purchase_order_items_id_seq', COALESCE((SELECT MAX(id) FROM p2_purchase_order_items), 0) + 1, false);

-- Convert vendor_po_settings
ALTER TABLE vendor_po_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE vendor_po_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME vendor_po_settings_id_seq RESTART WITH 1);
SELECT setval('vendor_po_settings_id_seq', COALESCE((SELECT MAX(id) FROM vendor_po_settings), 0) + 1, false);

-- Convert communication_logs
ALTER TABLE communication_logs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE communication_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME communication_logs_id_seq RESTART WITH 1);
SELECT setval('communication_logs_id_seq', COALESCE((SELECT MAX(id) FROM communication_logs), 0) + 1, false);

-- Convert customer_communications
ALTER TABLE customer_communications ALTER COLUMN id DROP DEFAULT;
ALTER TABLE customer_communications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME customer_communications_id_seq RESTART WITH 1);
SELECT setval('customer_communications_id_seq', COALESCE((SELECT MAX(id) FROM customer_communications), 0) + 1, false);

-- Convert pdf_documents
ALTER TABLE pdf_documents ALTER COLUMN id DROP DEFAULT;
ALTER TABLE pdf_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME pdf_documents_id_seq RESTART WITH 1);
SELECT setval('pdf_documents_id_seq', COALESCE((SELECT MAX(id) FROM pdf_documents), 0) + 1, false);

-- Convert order_attachments
ALTER TABLE order_attachments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE order_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_attachments_id_seq RESTART WITH 1);
SELECT setval('order_attachments_id_seq', COALESCE((SELECT MAX(id) FROM order_attachments), 0) + 1, false);

-- Convert nonconformance_records
ALTER TABLE nonconformance_records ALTER COLUMN id DROP DEFAULT;
ALTER TABLE nonconformance_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME nonconformance_records_id_seq RESTART WITH 1);
SELECT setval('nonconformance_records_id_seq', COALESCE((SELECT MAX(id) FROM nonconformance_records), 0) + 1, false);

-- Convert enhanced_form_categories
ALTER TABLE enhanced_form_categories ALTER COLUMN id DROP DEFAULT;
ALTER TABLE enhanced_form_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME enhanced_form_categories_id_seq RESTART WITH 1);
SELECT setval('enhanced_form_categories_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_form_categories), 0) + 1, false);

-- Convert enhanced_forms
ALTER TABLE enhanced_forms ALTER COLUMN id DROP DEFAULT;
ALTER TABLE enhanced_forms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME enhanced_forms_id_seq RESTART WITH 1);
SELECT setval('enhanced_forms_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_forms), 0) + 1, false);

-- Convert enhanced_form_versions
ALTER TABLE enhanced_form_versions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE enhanced_form_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME enhanced_form_versions_id_seq RESTART WITH 1);
SELECT setval('enhanced_form_versions_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_form_versions), 0) + 1, false);

-- Convert enhanced_form_submissions
ALTER TABLE enhanced_form_submissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE enhanced_form_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME enhanced_form_submissions_id_seq RESTART WITH 1);
SELECT setval('enhanced_form_submissions_id_seq', COALESCE((SELECT MAX(id) FROM enhanced_form_submissions), 0) + 1, false);

-- Convert p2_purchase_orders
ALTER TABLE p2_purchase_orders ALTER COLUMN id DROP DEFAULT;
ALTER TABLE p2_purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME p2_purchase_orders_id_seq RESTART WITH 1);
SELECT setval('p2_purchase_orders_id_seq', COALESCE((SELECT MAX(id) FROM p2_purchase_orders), 0) + 1, false);

-- Convert rfq_risk_assessments
ALTER TABLE rfq_risk_assessments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE rfq_risk_assessments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME rfq_risk_assessments_id_seq RESTART WITH 1);
SELECT setval('rfq_risk_assessments_id_seq', COALESCE((SELECT MAX(id) FROM rfq_risk_assessments), 0) + 1, false);

-- Convert p2_production_orders
ALTER TABLE p2_production_orders ALTER COLUMN id DROP DEFAULT;
ALTER TABLE p2_production_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME p2_production_orders_id_seq RESTART WITH 1);
SELECT setval('p2_production_orders_id_seq', COALESCE((SELECT MAX(id) FROM p2_production_orders), 0) + 1, false);

-- Convert bom_definitions
ALTER TABLE bom_definitions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE bom_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME bom_definitions_id_seq RESTART WITH 1);
SELECT setval('bom_definitions_id_seq', COALESCE((SELECT MAX(id) FROM bom_definitions), 0) + 1, false);

-- Convert bom_items
ALTER TABLE bom_items ALTER COLUMN id DROP DEFAULT;
ALTER TABLE bom_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME bom_items_id_seq RESTART WITH 1);
SELECT setval('bom_items_id_seq', COALESCE((SELECT MAX(id) FROM bom_items), 0) + 1, false);

-- Convert parts
ALTER TABLE parts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME parts_id_seq RESTART WITH 1);
SELECT setval('parts_id_seq', COALESCE((SELECT MAX(id) FROM parts), 0) + 1, false);

-- Convert boms
ALTER TABLE boms ALTER COLUMN id DROP DEFAULT;
ALTER TABLE boms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME boms_id_seq RESTART WITH 1);
SELECT setval('boms_id_seq', COALESCE((SELECT MAX(id) FROM boms), 0) + 1, false);

-- Convert bom_revisions
ALTER TABLE bom_revisions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE bom_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME bom_revisions_id_seq RESTART WITH 1);
SELECT setval('bom_revisions_id_seq', COALESCE((SELECT MAX(id) FROM bom_revisions), 0) + 1, false);

-- Convert bom_lines
ALTER TABLE bom_lines ALTER COLUMN id DROP DEFAULT;
ALTER TABLE bom_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME bom_lines_id_seq RESTART WITH 1);
SELECT setval('bom_lines_id_seq', COALESCE((SELECT MAX(id) FROM bom_lines), 0) + 1, false);

-- Convert order_id_reservations
ALTER TABLE order_id_reservations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE order_id_reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_id_reservations_id_seq RESTART WITH 1);
SELECT setval('order_id_reservations_id_seq', COALESCE((SELECT MAX(id) FROM order_id_reservations), 0) + 1, false);

-- Convert order_id_sequences
ALTER TABLE order_id_sequences ALTER COLUMN id DROP DEFAULT;
ALTER TABLE order_id_sequences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_id_sequences_id_seq RESTART WITH 1);
SELECT setval('order_id_sequences_id_seq', COALESCE((SELECT MAX(id) FROM order_id_sequences), 0) + 1, false);

-- Convert task_items
ALTER TABLE task_items ALTER COLUMN id DROP DEFAULT;
ALTER TABLE task_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME task_items_id_seq RESTART WITH 1);
SELECT setval('task_items_id_seq', COALESCE((SELECT MAX(id) FROM task_items), 0) + 1, false);

-- Convert kickbacks
ALTER TABLE kickbacks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE kickbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME kickbacks_id_seq RESTART WITH 1);
SELECT setval('kickbacks_id_seq', COALESCE((SELECT MAX(id) FROM kickbacks), 0) + 1, false);

-- Convert documents
ALTER TABLE documents ALTER COLUMN id DROP DEFAULT;
ALTER TABLE documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME documents_id_seq RESTART WITH 1);
SELECT setval('documents_id_seq', COALESCE((SELECT MAX(id) FROM documents), 0) + 1, false);

-- Convert document_tags
ALTER TABLE document_tags ALTER COLUMN id DROP DEFAULT;
ALTER TABLE document_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME document_tags_id_seq RESTART WITH 1);
SELECT setval('document_tags_id_seq', COALESCE((SELECT MAX(id) FROM document_tags), 0) + 1, false);

-- Convert document_collections
ALTER TABLE document_collections ALTER COLUMN id DROP DEFAULT;
ALTER TABLE document_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME document_collections_id_seq RESTART WITH 1);
SELECT setval('document_collections_id_seq', COALESCE((SELECT MAX(id) FROM document_collections), 0) + 1, false);

-- Convert po_products
ALTER TABLE po_products ALTER COLUMN id DROP DEFAULT;
ALTER TABLE po_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME po_products_id_seq RESTART WITH 1);
SELECT setval('po_products_id_seq', COALESCE((SELECT MAX(id) FROM po_products), 0) + 1, false);

-- Convert po_product_selections
ALTER TABLE po_product_selections ALTER COLUMN id DROP DEFAULT;
ALTER TABLE po_product_selections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME po_product_selections_id_seq RESTART WITH 1);
SELECT setval('po_product_selections_id_seq', COALESCE((SELECT MAX(id) FROM po_product_selections), 0) + 1, false);

-- Convert weekly_schedule_assignments
ALTER TABLE weekly_schedule_assignments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE weekly_schedule_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME weekly_schedule_assignments_id_seq RESTART WITH 1);
SELECT setval('weekly_schedule_assignments_id_seq', COALESCE((SELECT MAX(id) FROM weekly_schedule_assignments), 0) + 1, false);

-- Convert oem_priority_settings
ALTER TABLE oem_priority_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE oem_priority_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME oem_priority_settings_id_seq RESTART WITH 1);
SELECT setval('oem_priority_settings_id_seq', COALESCE((SELECT MAX(id) FROM oem_priority_settings), 0) + 1, false);

-- Convert departments
ALTER TABLE departments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME departments_id_seq RESTART WITH 1);
SELECT setval('departments_id_seq', COALESCE((SELECT MAX(id) FROM departments), 0) + 1, false);

-- Convert internal_messages
ALTER TABLE internal_messages ALTER COLUMN id DROP DEFAULT;
ALTER TABLE internal_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME internal_messages_id_seq RESTART WITH 1);
SELECT setval('internal_messages_id_seq', COALESCE((SELECT MAX(id) FROM internal_messages), 0) + 1, false);

-- Convert message_recipients
ALTER TABLE message_recipients ALTER COLUMN id DROP DEFAULT;
ALTER TABLE message_recipients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME message_recipients_id_seq RESTART WITH 1);
SELECT setval('message_recipients_id_seq', COALESCE((SELECT MAX(id) FROM message_recipients), 0) + 1, false);

-- Convert message_attachments
ALTER TABLE message_attachments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE message_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME message_attachments_id_seq RESTART WITH 1);
SELECT setval('message_attachments_id_seq', COALESCE((SELECT MAX(id) FROM message_attachments), 0) + 1, false);

-- Convert metal_accessories
ALTER TABLE metal_accessories ALTER COLUMN id DROP DEFAULT;
ALTER TABLE metal_accessories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME metal_accessories_id_seq RESTART WITH 1);
SELECT setval('metal_accessories_id_seq', COALESCE((SELECT MAX(id) FROM metal_accessories), 0) + 1, false);

-- Convert feature_selections
ALTER TABLE feature_selections ALTER COLUMN id DROP DEFAULT;
ALTER TABLE feature_selections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME feature_selections_id_seq RESTART WITH 1);
SELECT setval('feature_selections_id_seq', COALESCE((SELECT MAX(id) FROM feature_selections), 0) + 1, false);

-- Convert magic_link_tokens
ALTER TABLE magic_link_tokens ALTER COLUMN id DROP DEFAULT;
ALTER TABLE magic_link_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME magic_link_tokens_id_seq RESTART WITH 1);
SELECT setval('magic_link_tokens_id_seq', COALESCE((SELECT MAX(id) FROM magic_link_tokens), 0) + 1, false);

-- Convert oauth_states
ALTER TABLE oauth_states ALTER COLUMN id DROP DEFAULT;
ALTER TABLE oauth_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME oauth_states_id_seq RESTART WITH 1);
SELECT setval('oauth_states_id_seq', COALESCE((SELECT MAX(id) FROM oauth_states), 0) + 1, false);

-- Convert cutting_materials
ALTER TABLE cutting_materials ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_materials_id_seq RESTART WITH 1);
SELECT setval('cutting_materials_id_seq', COALESCE((SELECT MAX(id) FROM cutting_materials), 0) + 1, false);

-- Convert cutting_production_lines
ALTER TABLE cutting_production_lines ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_production_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_production_lines_id_seq RESTART WITH 1);
SELECT setval('cutting_production_lines_id_seq', COALESCE((SELECT MAX(id) FROM cutting_production_lines), 0) + 1, false);

-- Convert cutting_product_categories
ALTER TABLE cutting_product_categories ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_product_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_product_categories_id_seq RESTART WITH 1);
SELECT setval('cutting_product_categories_id_seq', COALESCE((SELECT MAX(id) FROM cutting_product_categories), 0) + 1, false);

-- Convert cutting_components
ALTER TABLE cutting_components ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_components_id_seq RESTART WITH 1);
SELECT setval('cutting_components_id_seq', COALESCE((SELECT MAX(id) FROM cutting_components), 0) + 1, false);

-- Convert cutting_packet_compositions
ALTER TABLE cutting_packet_compositions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_packet_compositions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_packet_compositions_id_seq RESTART WITH 1);
SELECT setval('cutting_packet_compositions_id_seq', COALESCE((SELECT MAX(id) FROM cutting_packet_compositions), 0) + 1, false);

-- Convert cutting_weekly_data
ALTER TABLE cutting_weekly_data ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_weekly_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_weekly_data_id_seq RESTART WITH 1);
SELECT setval('cutting_weekly_data_id_seq', COALESCE((SELECT MAX(id) FROM cutting_weekly_data), 0) + 1, false);

-- Convert cutting_cut_progress
ALTER TABLE cutting_cut_progress ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_cut_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_cut_progress_id_seq RESTART WITH 1);
SELECT setval('cutting_cut_progress_id_seq', COALESCE((SELECT MAX(id) FROM cutting_cut_progress), 0) + 1, false);

-- Convert cutting_fabric_inventory
ALTER TABLE cutting_fabric_inventory ALTER COLUMN id DROP DEFAULT;
ALTER TABLE cutting_fabric_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cutting_fabric_inventory_id_seq RESTART WITH 1);
SELECT setval('cutting_fabric_inventory_id_seq', COALESCE((SELECT MAX(id) FROM cutting_fabric_inventory), 0) + 1, false);

-- Convert controlled_documents
ALTER TABLE controlled_documents ALTER COLUMN id DROP DEFAULT;
ALTER TABLE controlled_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME controlled_documents_id_seq RESTART WITH 1);
SELECT setval('controlled_documents_id_seq', COALESCE((SELECT MAX(id) FROM controlled_documents), 0) + 1, false);

-- Convert document_version_history
ALTER TABLE document_version_history ALTER COLUMN id DROP DEFAULT;
ALTER TABLE document_version_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME document_version_history_id_seq RESTART WITH 1);
SELECT setval('document_version_history_id_seq', COALESCE((SELECT MAX(id) FROM document_version_history), 0) + 1, false);

-- Convert pdf_templates
ALTER TABLE pdf_templates ALTER COLUMN id DROP DEFAULT;
ALTER TABLE pdf_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME pdf_templates_id_seq RESTART WITH 1);
SELECT setval('pdf_templates_id_seq', COALESCE((SELECT MAX(id) FROM pdf_templates), 0) + 1, false);

-- Convert p2_employee_part_certifications
ALTER TABLE p2_employee_part_certifications ALTER COLUMN id DROP DEFAULT;
ALTER TABLE p2_employee_part_certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME p2_employee_part_certifications_id_seq RESTART WITH 1);
SELECT setval('p2_employee_part_certifications_id_seq', COALESCE((SELECT MAX(id) FROM p2_employee_part_certifications), 0) + 1, false);

-- Convert p2_part_certifications
ALTER TABLE p2_part_certifications ALTER COLUMN id DROP DEFAULT;
ALTER TABLE p2_part_certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME p2_part_certifications_id_seq RESTART WITH 1);
SELECT setval('p2_part_certifications_id_seq', COALESCE((SELECT MAX(id) FROM p2_part_certifications), 0) + 1, false);

