-- Phase 1 Foundation Closure
--
-- Seeds the cross-domain approval policies that are used by the enterprise
-- approval engine for WAD, estimating, procurement, inventory overrides,
-- NCR, engineering release, and contract/clause flowdown. Existing policies
-- are preserved, but their descriptions and active status are refreshed.

INSERT INTO escalation_policies (request_type, display_name, description, chain, requires_signature, reason_codes, is_active)
VALUES
  ('WAD_APPROVAL', 'WAD Approval',
   'Approval chain for Work Authorization Document release before production use.',
   '[{"role":"Production Supervisor","slaSeconds":14400},{"role":"Production Manager","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["SCOPE_VERIFIED","BUDGET_VERIFIED","ROUTING_VERIFIED","OTHER"]'::jsonb,
   true),
  ('WAD_EXCEPTION', 'WAD Exception',
   'Approval chain for WAD overrun, charge-code override, or late-release exception.',
   '[{"role":"Production Supervisor","slaSeconds":7200},{"role":"Production Manager","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["OVERRUN","CHARGE_CODE_OVERRIDE","LATE_RELEASE","CUSTOMER_HOT","OTHER"]'::jsonb,
   true),
  ('ESTIMATE_RELEASE', 'Estimate Release',
   'Approval chain for releasing an estimate to procurement, contract review, or production planning.',
   '[{"role":"Estimator","slaSeconds":14400},{"role":"Sales Manager","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["MARGIN_REVIEWED","TECHNICAL_SCOPE_REVIEWED","CUSTOMER_CHANGE","OTHER"]'::jsonb,
   true),
  ('PURCHASE_REQUISITION_APPROVAL', 'Purchase Requisition Approval',
   'Approval chain for purchase requisitions before PO creation.',
   '[{"role":"Purchasing","slaSeconds":14400},{"role":"Finance","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["BUDGET_CONFIRMED","SOLE_SOURCE","PROJECT_MATERIAL","INDIRECT_MATERIAL","OTHER"]'::jsonb,
   true),
  ('PROCUREMENT_DIRECT_PO_EXCEPTION', 'Direct PO Exception',
   'Approval chain for issuing a purchase order without an approved requisition.',
   '[{"role":"Purchasing","slaSeconds":7200},{"role":"Controller","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["EMERGENCY_BUY","CUSTOMER_HOT","SUPPLIER_WINDOW","OTHER"]'::jsonb,
   true),
  ('ENGINEERING_RELEASE', 'Engineering Release',
   'Approval chain for releasing an engineering-controlled artifact revision.',
   '[{"role":"Engineering","slaSeconds":14400},{"role":"Quality Manager","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["ECO_APPROVED","CUSTOMER_APPROVED","EFFECTIVITY_CONFIRMED","OTHER"]'::jsonb,
   true),
  ('ENGINEERING_ECO_APPROVAL', 'Engineering ECO Approval',
   'Approval chain for engineering change order approval before implementation or release.',
   '[{"role":"Engineering","slaSeconds":14400},{"role":"Quality Manager","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["FORM_FIT_FUNCTION","PROCESS_CHANGE","CUSTOMER_FLOWDOWN","CORRECTION","OTHER"]'::jsonb,
   true),
  ('CONTRACT_CLAUSE_FLOWDOWN', 'Contract Clause Flowdown',
   'Approval chain for contract-review clause applicability and downstream FAR/DFARS flowdown.',
   '[{"role":"Contracts","slaSeconds":14400},{"role":"Purchasing","slaSeconds":28800},{"role":"Director of Operations","slaSeconds":86400,"isBackstop":true}]'::jsonb,
   true,
   '["FAR","DFARS","QUALITY_CLAUSE","CUSTOMER_SPECIFIC","OTHER"]'::jsonb,
   true)
ON CONFLICT (request_type) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  chain = EXCLUDED.chain,
  requires_signature = EXCLUDED.requires_signature,
  reason_codes = EXCLUDED.reason_codes,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
