-- Runtime repair for P1 NCR saves.
-- Earlier broad migrations introduced these columns alongside other objects.
-- If those files were skipped or failed in an older environment, the dashboard
-- can still list records while create/update fails when Drizzle returns the full
-- nonconformance_records shape.

ALTER TABLE nonconformance_records
  ADD COLUMN IF NOT EXISTS rma_number text,
  ADD COLUMN IF NOT EXISTS additional_order_ids text[] DEFAULT ARRAY[]::text[],
  ADD COLUMN IF NOT EXISTS additional_serial_numbers text[] DEFAULT ARRAY[]::text[],
  ADD COLUMN IF NOT EXISTS date_received date,
  ADD COLUMN IF NOT EXISTS p1_or_p2 text NOT NULL DEFAULT 'P1',
  ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'return',
  ADD COLUMN IF NOT EXISTS sku text,
  ADD COLUMN IF NOT EXISTS customer_id integer,
  ADD COLUMN IF NOT EXISTS disposition_action text,
  ADD COLUMN IF NOT EXISTS resolution_type text,
  ADD COLUMN IF NOT EXISTS new_order_id text,
  ADD COLUMN IF NOT EXISTS use_order_address boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS repair_address jsonb,
  ADD COLUMN IF NOT EXISTS shipping_status text,
  ADD COLUMN IF NOT EXISTS tracking_number text,
  ADD COLUMN IF NOT EXISTS shipping_carrier text,
  ADD COLUMN IF NOT EXISTS shipped_date date,
  ADD COLUMN IF NOT EXISTS customer_notified boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS viewed_by jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_confirmed_at timestamp,
  ADD COLUMN IF NOT EXISTS last_confirmed_by_user_id integer,
  ADD COLUMN IF NOT EXISTS confirmation_note text,
  ADD COLUMN IF NOT EXISTS attention_risk text,
  ADD COLUMN IF NOT EXISTS containment_action text,
  ADD COLUMN IF NOT EXISTS containment_owner text,
  ADD COLUMN IF NOT EXISTS containment_due_date date,
  ADD COLUMN IF NOT EXISTS containment_completed_at timestamp,
  ADD COLUMN IF NOT EXISTS root_cause text,
  ADD COLUMN IF NOT EXISTS root_cause_method text,
  ADD COLUMN IF NOT EXISTS corrective_action text,
  ADD COLUMN IF NOT EXISTS preventive_action text,
  ADD COLUMN IF NOT EXISTS capa_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS capa_id uuid,
  ADD COLUMN IF NOT EXISTS disposition_rationale text,
  ADD COLUMN IF NOT EXISTS disposition_approved_by_user_id integer,
  ADD COLUMN IF NOT EXISTS disposition_approved_by_display_name text,
  ADD COLUMN IF NOT EXISTS disposition_approved_at timestamp,
  ADD COLUMN IF NOT EXISTS effectiveness_review text,
  ADD COLUMN IF NOT EXISTS effectiveness_status text DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS effectiveness_reviewed_by_user_id integer,
  ADD COLUMN IF NOT EXISTS effectiveness_reviewed_by_display_name text,
  ADD COLUMN IF NOT EXISTS effectiveness_reviewed_at timestamp,
  ADD COLUMN IF NOT EXISTS recurrence_detected boolean DEFAULT false;
