import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Camera, CheckCircle2, ChevronRight, CircleAlert, PackageSearch, Plus, Search, Wrench } from 'lucide-react';
import { apiRequest } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useToast } from '@/hooks/use-toast';

const json = async (url: string, options?: any) => (await apiRequest(url, options)).json();
const blankProduct = { productName: '', modelNumber: '', productPartNumber: '', revision: '', customer: '', notes: '' };
const blankItem = { itemName: '', enteredPartNumber: '', quantity: 1, assemblyName: '', parentAssemblyName: '', physicalLocation: '', threadSize: '', length: '', headStyle: '', driveStyle: '', materialFinish: '', additionalDetails: '', notes: '' };

function SuggestionInput({ value, onChange, placeholder, options, listId }: any) {
  return <><Input list={listId} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}/><datalist id={listId}>{options.map((option:string)=><option key={option} value={option}/>)}</datalist></>;
}

export default function ProductTeardown() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showNew, setShowNew] = useState(false);
  const [product, setProduct] = useState(blankProduct);
  const [item, setItem] = useState(blankItem);
  const [assemblyFilter, setAssemblyFilter] = useState('all');
  const [locationFilter, setLocationFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [verifyItem, setVerifyItem] = useState<any>(null);
  const [matchOptions, setMatchOptions] = useState<any[]>([]);

  const { data: sessions = [] } = useQuery<any[]>({ queryKey: ['/api/product-teardowns'], queryFn: () => json('/api/product-teardowns') });
  const { data: details, isLoading } = useQuery<any>({ queryKey: ['/api/product-teardowns', selectedId], queryFn: () => json(`/api/product-teardowns/${selectedId}`), enabled: Boolean(selectedId) });
  const { data: suggestions = { names: [], assemblies: [], locations: [], partNumbers: [] } } = useQuery<any>({ queryKey: ['/api/product-teardowns/suggestions'], queryFn: () => json('/api/product-teardowns/suggestions') });
  const { data: comparison } = useQuery<any>({ queryKey: ['/api/product-teardowns', selectedId, 'bom-comparison'], queryFn: () => json(`/api/product-teardowns/${selectedId}/bom-comparison`), enabled: Boolean(selectedId) });
  const values = (key:string) => (suggestions[key] ?? []).map((row:any) => row.value).filter(Boolean);

  const createSession = useMutation({ mutationFn: () => json('/api/product-teardowns', { method: 'POST', body: product }), onSuccess: (created) => { queryClient.invalidateQueries({ queryKey: ['/api/product-teardowns'] }); setSelectedId(created.id); setShowNew(false); setProduct(blankProduct); toast({ title: 'Product teardown created' }); } });
  const addItem = useMutation({ mutationFn: () => json(`/api/product-teardowns/${selectedId}/items`, { method: 'POST', body: item }), onSuccess: (result) => { queryClient.invalidateQueries({ queryKey: ['/api/product-teardowns', selectedId] }); queryClient.invalidateQueries({ queryKey: ['/api/product-teardowns/suggestions'] }); queryClient.invalidateQueries({ queryKey: ['/api/product-teardowns', selectedId, 'bom-comparison'] }); setItem(blankItem); toast({ title: result.item.inventory_match_state === 'found' ? `Matched inventory part ${result.item.inventory_part_number}` : result.item.inventory_match_state === 'possible' ? 'Possible inventory match found—please verify' : 'Item captured' }); } });
  const toggleMatch = useMutation({ mutationFn: ({ row, checked }: any) => json(`/api/product-teardowns/${selectedId}/items/${row.id}/match`, { method: 'PATCH', body: { inventoryItemId: checked ? row.inventory_item_id : null, confirmed: checked } }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['/api/product-teardowns', selectedId] }) });
  const uploadPhoto = async (file: File, itemId?: string) => { const body = new FormData(); body.append('photo', file); if (itemId) body.append('itemId', itemId); await json(`/api/product-teardowns/${selectedId}/photos`, { method: 'POST', body }); queryClient.invalidateQueries({ queryKey: ['/api/product-teardowns', selectedId] }); toast({ title: 'Photo attached' }); };
  const openVerification = async (row:any) => { setVerifyItem(row); setMatchOptions(await json(`/api/product-teardowns/${selectedId}/items/${row.id}/matches`)); };

  const items = details?.items ?? [];
  const assemblies = [...new Set(items.map((row:any)=>row.assembly_name).filter(Boolean))] as string[];
  const locations = [...new Set(items.map((row:any)=>row.physical_location).filter(Boolean))] as string[];
  const filtered = items.filter((row:any) => (assemblyFilter === 'all' || row.assembly_name === assemblyFilter) && (locationFilter === 'all' || row.physical_location === locationFilter) && (!search || `${row.item_name} ${row.entered_part_number ?? ''}`.toLowerCase().includes(search.toLowerCase())));
  const consolidated = useMemo(() => {
    const groups = new Map<string, any>();
    for (const row of filtered) { const key = row.item_name.trim().toLowerCase(); const current = groups.get(key) ?? { ...row, total: 0, occurrences: [] }; current.total += Number(row.quantity); current.occurrences.push(row); groups.set(key, current); }
    return [...groups.values()].sort((a,b)=>a.item_name.localeCompare(b.item_name));
  }, [filtered]);

  if (!selectedId) return <div className="mx-auto max-w-6xl space-y-6 p-6">
    <div className="flex items-start justify-between"><div><h1 className="text-3xl font-semibold">Product Teardown</h1><p className="text-muted-foreground">Capture what you observe while disassembling a product, then compare it with inventory and the latest BOM.</p></div><Button onClick={()=>setShowNew(!showNew)}><Plus className="mr-2 h-4 w-4"/>New teardown</Button></div>
    {showNew && <Card><CardHeader><CardTitle>New product</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">
      <Input placeholder="Product name *" value={product.productName} onChange={e=>setProduct({...product,productName:e.target.value})}/><Input placeholder="Model number" value={product.modelNumber} onChange={e=>setProduct({...product,modelNumber:e.target.value})}/><Input placeholder="Product / AG part number" value={product.productPartNumber} onChange={e=>setProduct({...product,productPartNumber:e.target.value})}/><Input placeholder="Revision" value={product.revision} onChange={e=>setProduct({...product,revision:e.target.value})}/><Input placeholder="Customer" value={product.customer} onChange={e=>setProduct({...product,customer:e.target.value})}/><Textarea placeholder="Notes" value={product.notes} onChange={e=>setProduct({...product,notes:e.target.value})}/><Button disabled={!product.productName || createSession.isPending} onClick={()=>createSession.mutate()}>Create teardown</Button>
    </CardContent></Card>}
    <div className="grid gap-4 md:grid-cols-2">{sessions.map((session:any)=><Card key={session.id} className="cursor-pointer hover:border-primary" onClick={()=>setSelectedId(session.id)}><CardContent className="flex items-center justify-between p-5"><div><div className="font-semibold">{session.product_name}</div><div className="text-sm text-muted-foreground">{session.model_number || 'No model'} {session.revision ? `• Rev ${session.revision}` : ''}</div></div><ChevronRight/></CardContent></Card>)}</div>
  </div>;

  if (isLoading || !details) return <div className="p-8">Loading teardown…</div>;
  return <div className="mx-auto max-w-[1500px] space-y-5 p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Button variant="ghost" className="mb-2 px-0" onClick={()=>setSelectedId(null)}>← All teardowns</Button><h1 className="text-3xl font-semibold">{details.product_name}</h1><p className="text-muted-foreground">{[details.model_number, details.product_part_number, details.revision && `Rev ${details.revision}`].filter(Boolean).join(' • ')}</p><div className="mt-3 flex gap-2">{details.photos?.map((photo:any)=><img key={photo.id} src={photo.file_url} alt="Product teardown" className="h-20 w-20 rounded-md border object-cover"/>)}</div></div><label className="cursor-pointer"><Input className="hidden" type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadPhoto(e.target.files[0])}/><Button asChild variant="outline"><span><Camera className="mr-2 h-4 w-4"/>Product photo</span></Button></label></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Wrench className="h-5 w-5"/>Capture an observed item</CardTitle></CardHeader><CardContent className="space-y-4">
      <div className="grid gap-3 md:grid-cols-4"><SuggestionInput listId="teardown-names" placeholder="Item name / description *" options={values('names')} value={item.itemName} onChange={(v:string)=>setItem({...item,itemName:v})}/><SuggestionInput listId="teardown-parts" placeholder="Observed part # (optional)" options={values('partNumbers')} value={item.enteredPartNumber} onChange={(v:string)=>setItem({...item,enteredPartNumber:v})}/><Input type="number" min="0.001" step="any" placeholder="Quantity" value={item.quantity} onChange={e=>setItem({...item,quantity:Number(e.target.value)})}/><SuggestionInput listId="teardown-location" placeholder="Location (Front, underside…)" options={values('locations')} value={item.physicalLocation} onChange={(v:string)=>setItem({...item,physicalLocation:v})}/><SuggestionInput listId="teardown-assembly" placeholder="Assembly" options={values('assemblies')} value={item.assemblyName} onChange={(v:string)=>setItem({...item,assemblyName:v})}/><SuggestionInput listId="teardown-parent" placeholder="Parent assembly" options={values('assemblies')} value={item.parentAssemblyName} onChange={(v:string)=>setItem({...item,parentAssemblyName:v})}/><Input placeholder="Thread size" value={item.threadSize} onChange={e=>setItem({...item,threadSize:e.target.value})}/><Input placeholder="Length" value={item.length} onChange={e=>setItem({...item,length:e.target.value})}/><Input placeholder="Head style" value={item.headStyle} onChange={e=>setItem({...item,headStyle:e.target.value})}/><Input placeholder="Drive style" value={item.driveStyle} onChange={e=>setItem({...item,driveStyle:e.target.value})}/><Input placeholder="Material / finish" value={item.materialFinish} onChange={e=>setItem({...item,materialFinish:e.target.value})}/><Input placeholder="Additional size/details" value={item.additionalDetails} onChange={e=>setItem({...item,additionalDetails:e.target.value})}/></div>
      <Textarea placeholder="Notes about this occurrence" value={item.notes} onChange={e=>setItem({...item,notes:e.target.value})}/><Button disabled={!item.itemName || addItem.isPending} onClick={()=>addItem.mutate()}><Plus className="mr-2 h-4 w-4"/>Add occurrence</Button>
    </CardContent></Card>
    <div className="flex flex-wrap gap-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search captured items" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={assemblyFilter} onValueChange={setAssemblyFilter}><SelectTrigger className="w-56"><SelectValue placeholder="All assemblies"/></SelectTrigger><SelectContent><SelectItem value="all">All assemblies</SelectItem>{assemblies.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={locationFilter} onValueChange={setLocationFilter}><SelectTrigger className="w-56"><SelectValue placeholder="All locations"/></SelectTrigger><SelectContent><SelectItem value="all">All locations</SelectItem>{locations.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
    <Tabs defaultValue="occurrences"><TabsList><TabsTrigger value="occurrences">Individual occurrences ({filtered.length})</TabsTrigger><TabsTrigger value="consolidated">Consolidated parts ({consolidated.length})</TabsTrigger><TabsTrigger value="bom">Latest BOM check</TabsTrigger></TabsList>
      <TabsContent value="occurrences"><Card><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Qty</TableHead><TableHead>Assembly</TableHead><TableHead>Location</TableHead><TableHead>Details</TableHead><TableHead>Inventory</TableHead><TableHead>Photos</TableHead></TableRow></TableHeader><TableBody>{filtered.map((row:any)=><TableRow key={row.id}><TableCell className="font-medium">{row.item_name}<div className="text-xs text-muted-foreground">{row.entered_part_number}</div></TableCell><TableCell>{Number(row.quantity)}</TableCell><TableCell>{row.parent_assembly_name && <span className="text-muted-foreground">{row.parent_assembly_name} › </span>}{row.assembly_name || '—'}</TableCell><TableCell>{row.physical_location || '—'}</TableCell><TableCell className="max-w-64 text-sm">{[row.thread_size,row.length,row.head_style,row.drive_style,row.material_finish,row.additional_details].filter(Boolean).join(' • ') || '—'}</TableCell><TableCell>{row.inventory_match_state==='found'?<div className="flex items-center gap-2"><Checkbox checked={row.inventory_match_confirmed} onCheckedChange={checked=>toggleMatch.mutate({row,checked:Boolean(checked)})}/><div><Badge className="bg-emerald-600"><CheckCircle2 className="mr-1 h-3 w-3"/>Found</Badge><div className="mt-1 text-xs font-medium">{row.inventory_part_number}</div></div></div>:row.inventory_match_state==='possible'?<Button size="sm" variant="outline" className="border-amber-500 text-amber-700" onClick={()=>openVerification(row)}><CircleAlert className="mr-1 h-3 w-3"/>Possible match—verify</Button>:<Badge variant="secondary">Not found</Badge>}</TableCell><TableCell><div className="flex items-center gap-2">{row.photos?.slice(0,3).map((photo:any)=><img key={photo.id} src={photo.file_url} alt="Captured part" className="h-10 w-10 rounded object-cover"/>)}<label className="cursor-pointer"><Input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&uploadPhoto(e.target.files[0],row.id)}/><Camera className="h-5 w-5 text-muted-foreground"/></label></div></TableCell></TableRow>)}</TableBody></Table></Card></TabsContent>
      <TabsContent value="consolidated"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{consolidated.map((row:any)=><Card key={row.item_name}><CardContent className="p-5"><div className="flex justify-between gap-3"><div className="font-semibold">{row.item_name}</div><Badge>{row.total} total</Badge></div><div className="mt-3 space-y-2 text-sm">{row.occurrences.map((occ:any)=><div key={occ.id} className="rounded-md bg-muted p-2">{Number(occ.quantity)} × {occ.assembly_name || 'No assembly'} · {occ.physical_location || 'No location'}</div>)}</div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="bom"><Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageSearch className="h-5 w-5"/>Latest released BOM {comparison?.revision && <Badge>Rev {comparison.revision}</Badge>}</CardTitle></CardHeader><CardContent>{!comparison?.revision?<p className="text-muted-foreground">No latest released BOM was found for product part number “{details.product_part_number || 'not entered'}”.</p>:<div className="grid gap-5 md:grid-cols-3"><Comparison title="Observed, missing from BOM" items={comparison.missingFromBom} render={(v:any)=>v.item_name}/><Comparison title="BOM item not observed" items={comparison.bomOnly} render={(v:any)=>`${v.child_name_snapshot || v.child_part_ag_number} (${v.child_part_ag_number})`}/><Comparison title="Possible match—verify" items={comparison.possible} render={(v:any)=>`${v.item.item_name} ↔ ${v.bomLine.child_name_snapshot || v.bomLine.child_part_ag_number}`}/></div>}</CardContent></Card></TabsContent>
    </Tabs>
    <Dialog open={Boolean(verifyItem)} onOpenChange={(open)=>!open&&setVerifyItem(null)}><DialogContent><DialogHeader><DialogTitle>Verify inventory match</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Choose the inventory item that matches “{verifyItem?.item_name}”. The inventory AG part number will be retained on the captured item.</p><div className="space-y-2">{matchOptions.map((option:any)=><button key={option.id} className="flex w-full items-center justify-between rounded-md border p-3 text-left hover:border-primary" onClick={()=>{toggleMatch.mutate({row:{...verifyItem,inventory_item_id:option.id},checked:true});setVerifyItem(null);}}><span><span className="font-medium">{option.name}</span><span className="block text-xs text-muted-foreground">{option.description}</span></span><Badge variant="outline">{option.ag_part_number}</Badge></button>)}</div></DialogContent></Dialog>
  </div>;
}

function Comparison({ title, items, render }: any) { return <div><h3 className="mb-2 font-semibold">{title} <Badge variant="secondary">{items?.length ?? 0}</Badge></h3><div className="space-y-2">{(items ?? []).map((item:any,index:number)=><div key={index} className="rounded-md border p-3 text-sm">{render(item)}</div>)}{!items?.length&&<p className="text-sm text-muted-foreground">None</p>}</div></div>; }
