/**
 * Regression guard for the employee portal token system.
 *
 * Ensures that the HMAC-signed token generated by generatePortalToken is
 * accepted by validatePortalToken, and that the deprecated DB-backed path
 * (generateEmployeePortalToken) is NOT connected to the validation middleware.
 *
 * These tests prevent the two token systems from silently diverging again.
 */

import { describe, it, expect, vi, beforeAll, afterAll } from 'vitest';

// ---------------------------------------------------------------------------
// All module mocks must be declared before any imports that resolve the graph
// ---------------------------------------------------------------------------

vi.mock('../db', () => ({
  db: {
    select: vi.fn(),
    insert: vi.fn(),
    update: vi.fn(),
    execute: vi.fn(),
  },
  pool: { query: vi.fn() },
  pgPool: { query: vi.fn() },
}));

// ---------------------------------------------------------------------------
// Imports (after mocks are hoisted)
// ---------------------------------------------------------------------------

import { db } from '../db';
import { DatabaseStorage } from '../storage';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const TEST_SECRET = 'test-portal-secret-32-bytes-long!';
const EMPLOYEE_ID = 42;

function makeSelectChain(rows: unknown[]) {
  const terminal = {
    where: vi.fn().mockResolvedValue(rows),
    limit: vi.fn().mockResolvedValue(rows),
    orderBy: vi.fn().mockResolvedValue(rows),
    then: (
      onFulfilled: (v: unknown) => unknown,
      onRejected: (e: unknown) => unknown,
    ) => Promise.resolve(rows).then(onFulfilled, onRejected),
  };
  return {
    from: vi.fn().mockReturnValue(terminal),
    set: vi.fn().mockReturnValue({ where: vi.fn().mockResolvedValue([]) }),
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Portal token round-trip (HMAC-signed path)', () => {
  let originalSecret: string | undefined;
  let storage: DatabaseStorage;

  beforeAll(() => {
    originalSecret = process.env.PORTAL_TOKEN_SECRET;
    process.env.PORTAL_TOKEN_SECRET = TEST_SECRET;
    storage = new DatabaseStorage();
  });

  afterAll(() => {
    if (originalSecret === undefined) {
      delete process.env.PORTAL_TOKEN_SECRET;
    } else {
      process.env.PORTAL_TOKEN_SECRET = originalSecret;
    }
  });

  it('generatePortalToken produces a token starting with "portal_"', async () => {
    const token = await storage.generatePortalToken(EMPLOYEE_ID);
    expect(token).toMatch(/^portal_/);
  });

  it('generatePortalToken embeds a body and HMAC signature separated by "."', async () => {
    const token = await storage.generatePortalToken(EMPLOYEE_ID);
    const rest = token.substring('portal_'.length);
    expect(rest).toContain('.');
    const parts = rest.split('.');
    expect(parts).toHaveLength(2);
    expect(parts[0].length).toBeGreaterThan(0);
    expect(parts[1].length).toBeGreaterThan(0);
  });

  it('validatePortalToken accepts a freshly generated token and returns the correct employeeId', async () => {
    // Stub the getEmployee lookup that validatePortalToken performs
    vi.mocked(db.select).mockReturnValue(
      makeSelectChain([{ id: EMPLOYEE_ID, isActive: true }]) as ReturnType<typeof db.select>,
    );

    const token = await storage.generatePortalToken(EMPLOYEE_ID);
    const result = await storage.validatePortalToken(token);

    expect(result.isValid).toBe(true);
    expect(result.employeeId).toBe(EMPLOYEE_ID);
  });

  it('validatePortalToken rejects a token with a tampered signature', async () => {
    const token = await storage.generatePortalToken(EMPLOYEE_ID);

    // Flip the last character of the signature to simulate tampering
    const tampered = token.slice(0, -1) + (token.endsWith('A') ? 'B' : 'A');
    const result = await storage.validatePortalToken(tampered);

    expect(result.isValid).toBe(false);
  });

  it('validatePortalToken rejects an expired token', async () => {
    // Build a token whose expiresAt is in the past
    const crypto = await import('crypto');
    const payload = {
      employeeId: EMPLOYEE_ID,
      expiresAt: Date.now() - 1000, // 1 second in the past
      random: crypto.randomBytes(16).toString('hex'),
    };
    const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
    const sig = crypto
      .createHmac('sha256', TEST_SECRET)
      .update(body)
      .digest('base64url');
    const expiredToken = `portal_${body}.${sig}`;

    const result = await storage.validatePortalToken(expiredToken);

    expect(result.isValid).toBe(false);
    expect(result.reason).toMatch(/expired/i);
  });

  it('validatePortalToken rejects a plain nanoid token (DB-backed format)', async () => {
    // Simulate a DB-backed nanoid that does NOT start with "portal_"
    const nanoidToken = 'Uv38ByGCZU8WP18PmiqtnPMpFBGH0W2L'; // 32-char opaque ID

    const result = await storage.validatePortalToken(nanoidToken);

    expect(result.isValid).toBe(false);
  });

  it('validatePortalToken rejects a token when PORTAL_TOKEN_SECRET is not set', async () => {
    delete process.env.PORTAL_TOKEN_SECRET;

    // Build a valid-looking signed token (signed with the known secret)
    const token = await (async () => {
      const crypto = await import('crypto');
      const payload = {
        employeeId: EMPLOYEE_ID,
        expiresAt: Date.now() + 60_000,
        random: crypto.randomBytes(16).toString('hex'),
      };
      const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
      const sig = crypto
        .createHmac('sha256', TEST_SECRET)
        .update(body)
        .digest('base64url');
      return `portal_${body}.${sig}`;
    })();

    const result = await storage.validatePortalToken(token);

    expect(result.isValid).toBe(false);

    // Restore secret for subsequent tests
    process.env.PORTAL_TOKEN_SECRET = TEST_SECRET;
  });
});
