import { PDFDocument, StandardFonts } from 'pdf-lib';
import { PDFParse } from 'pdf-parse';
import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('../storage', () => ({
  storage: {
    getVendorPO: vi.fn(),
    getVendor: vi.fn(),
    getVendorPOItems: vi.fn(),
    getCompanySettings: vi.fn(),
    getVendorPOSettings: vi.fn(),
    getPOOptionalSettings: vi.fn(),
  },
}));

import { storage } from '../storage';
import { generateVendorPoPdf, wrapVendorPoText } from '../utils/pdf/vendorPoPdf';

describe('vendor PO/RFQ PDF generator', () => {
  beforeEach(() => {
    vi.mocked(storage.getVendorPO).mockResolvedValue({
      id: 42,
      vendorId: 7,
      poNumber: null,
      orderDate: '2026-06-10',
      createdAt: '2026-06-10',
      expectedDeliveryDate: '2026-06-17',
      shipVia: 'UPS',
      status: 'RFQ Sent',
      notes: 'Please quote price and availability.',
      totalCost: null,
      shippingCost: null,
    } as any);
    vi.mocked(storage.getVendor).mockResolvedValue({
      id: 7,
      name: "Glenn's Metal Supplies",
      street: '100 Industrial Way',
      city: 'Huntsville',
      state: 'AL',
      zip_code: '35801',
      phone: '256-555-1234',
      email: 'sales@example.com',
      contactPerson: 'Glenn',
      termsAndConditions: 'Quote valid for 30 days.',
      paymentTerms: 'Net 30',
      shippingInstructions: 'Ship complete.',
    } as any);
    vi.mocked(storage.getVendorPOItems).mockResolvedValue([
      {
        lineNumber: 1,
        supplierPartNumber: '227',
        description: 'Metal, aluminum 1 x 1 1/2 x 3 3/4',
        notes: 'PR-115: 1 requested by glennj (Paint)',
        quantity: '2',
        unitPrice: '12.5',
        vendorUnit: 'EA',
      },
    ] as any);
    vi.mocked(storage.getCompanySettings).mockResolvedValue({
      companyName: 'AG Composites',
      companyAddress: '101 AG Way\nOwens Cross Roads, AL',
      companyPhone: '256-723-8381',
      companyEmail: 'glenn@agadvanced.com',
      companyWebsite: 'agcomposites.com',
    } as any);
    vi.mocked(storage.getVendorPOSettings).mockResolvedValue({
      contactName: 'Laurie Tandy',
      contactTitle: 'Purchasing',
      contactPhone: '256-723-8381',
      contactEmail: 'glenn@agadvanced.com',
      returnEmail: 'glenn@agadvanced.com',
    } as any);
    vi.mocked(storage.getPOOptionalSettings).mockResolvedValue([
      { name: 'Certification', statement: 'Certificate of conformance required.' },
    ] as any);
  });

  it('renders the preview-style RFQ PDF without falling back to the old attachment stub', async () => {
    const pdfBuffer = await generateVendorPoPdf(42);

    expect(pdfBuffer.subarray(0, 4).toString()).toBe('%PDF');

    const pdf = await PDFDocument.load(pdfBuffer);
    expect(pdf.getPageCount()).toBeGreaterThanOrEqual(1);

    const parser = new PDFParse({ data: pdfBuffer });
    try {
      const extracted = await parser.getText();
      expect(extracted.text).toContain('Glenn Jones');
      expect(extracted.text).toContain('Requested Delivery Date');
      expect(extracted.text).not.toContain('RFQ Sent');
      expect(extracted.text).not.toContain('Laurie');
      expect(extracted.text).not.toContain('Laurie Tandy');
      expect(extracted.text).not.toContain('Generated by EPOCH');
      expect(extracted.text).not.toContain('PR-115');
      expect(extracted.text).not.toContain('requested by glennj');
    } finally {
      await parser.destroy();
    }
  });

  it('watermarks every retained voided PO PDF as VOID', async () => {
    vi.mocked(storage.getVendorPO).mockResolvedValue({
      id: 42,
      vendorId: 7,
      poNumber: 'VPO-26001',
      orderDate: '2026-06-10',
      createdAt: '2026-06-10',
      status: 'Voided',
      voidedAt: '2026-07-29T12:00:00.000Z',
      voidReason: 'Created for the wrong supplier',
      totalCost: 25,
      shippingCost: 0,
    } as any);

    const pdfBuffer = await generateVendorPoPdf(42);
    const parser = new PDFParse({ data: pdfBuffer });
    try {
      const extracted = await parser.getText();
      expect(extracted.text).toContain('VOID');
    } finally {
      await parser.destroy();
    }
  });

  it('keeps an issued PO DPAS rating in the first-page metadata panel', async () => {
    vi.mocked(storage.getVendorPO).mockResolvedValue({
      id: 42,
      vendorId: 7,
      poNumber: 'VPO-26093',
      orderDate: '2026-08-24',
      createdAt: '2026-08-24',
      expectedDeliveryDate: '2026-09-14',
      shipVia: 'UPS',
      status: 'Sent',
      issueDpasRated: true,
      issueDpasRating: 'DO-A7',
      totalCost: 9468,
      shippingCost: 0,
    } as any);
    vi.mocked(storage.getVendorPOItems).mockResolvedValue(
      Array.from({ length: 28 }, (_, index) => ({
        lineNumber: index + 1,
        supplierPartNumber: `PART-${index + 1}`,
        description: `Production material line ${index + 1}`,
        quantity: '1',
        unitPrice: '338.14',
        vendorUnit: 'EA',
      })) as any
    );

    const pdfBuffer = await generateVendorPoPdf(42);
    const pdf = await PDFDocument.load(pdfBuffer);
    expect(pdf.getPageCount()).toBeGreaterThan(1);

    const parser = new PDFParse({ data: pdfBuffer });
    try {
      const firstPage = await parser.getText({ partial: [1] });
      expect(firstPage.text).toContain('DPAS Rating');
      expect(firstPage.text).toContain('DO-A7');
    } finally {
      await parser.destroy();
    }
  });

  it('keeps the complete sample metal dimension on one line in the widened description column', async () => {
    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const description = 'Metal, aluminum 1 x 1 1/2 x 3 3/4';

    expect(wrapVendorPoText(description, 164, font, 10.5)).toEqual([description]);
  });

  it('never separates the whole number from its fractional dimension when wrapping', async () => {
    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const lines = wrapVendorPoText('Aluminum angle 1 x 1 1/2 x 3 3/4 finished', 118, font, 10.5);

    expect(lines.join('|')).not.toMatch(/3\|3\/4/);
    expect(lines.some((line) => line.includes('3 3/4'))).toBe(true);
    expect(lines.join('|')).not.toMatch(/1\|1\/2/);
  });
});
