import { db } from '../../db';
import {
  edriEvidencePackets,
  edriDomainScores,
  edriRedFlags,
  edriRemediationItems,
  edriScoreSnapshots,
  InsertEdriEvidencePacket,
} from '../../schema';
import { eq, and } from 'drizzle-orm';
import JSZip from 'jszip';
import { ObjectStorageService } from '../../replit_integrations/object_storage';

const objectStorage = new ObjectStorageService();

export async function requestEvidencePacket(
  snapshotId: number,
  domainKey: string | null,
  userId: number,
  userDisplayName: string,
): Promise<number> {
  const insert: InsertEdriEvidencePacket = {
    snapshotId,
    domainKey: domainKey ?? null,
    requestedByUserId: userId,
    requestedByDisplayName: userDisplayName,
    status: 'PENDING',
    completedAt: null,
    storagePath: null,
    errorMessage: null,
  };
  const [packet] = await db.insert(edriEvidencePackets).values(insert).returning();

  // Trigger generation asynchronously — do not await
  generateEvidencePacket(packet.id, snapshotId, domainKey).catch(err => {
    console.error('Evidence packet generation failed:', err);
  });

  return packet.id;
}

export async function generateEvidencePacket(
  packetId: number,
  snapshotId: number,
  domainKey: string | null,
): Promise<void> {
  await db.update(edriEvidencePackets)
    .set({ status: 'GENERATING' })
    .where(eq(edriEvidencePackets.id, packetId));

  try {
    const snapshots = await db.select().from(edriScoreSnapshots)
      .where(eq(edriScoreSnapshots.id, snapshotId)).limit(1);
    const snapshot = snapshots[0];

    // Build filtered query conditions
    const domainCondition = domainKey
      ? and(eq(edriDomainScores.snapshotId, snapshotId), eq(edriDomainScores.domainKey, domainKey))
      : eq(edriDomainScores.snapshotId, snapshotId);

    const flagCondition = domainKey
      ? and(eq(edriRedFlags.snapshotId, snapshotId), eq(edriRedFlags.domainKey, domainKey))
      : eq(edriRedFlags.snapshotId, snapshotId);

    const remCondition = domainKey
      ? and(eq(edriRemediationItems.snapshotId, snapshotId), eq(edriRemediationItems.domainKey, domainKey))
      : eq(edriRemediationItems.snapshotId, snapshotId);

    const [domainScores, flags, remItems] = await Promise.all([
      db.select().from(edriDomainScores).where(domainCondition),
      db.select().from(edriRedFlags).where(flagCondition),
      db.select().from(edriRemediationItems).where(remCondition),
    ]);

    // Build ZIP with multiple files
    const zip = new JSZip();
    const folder = domainKey ? `edri-evidence-snapshot-${snapshotId}-${domainKey}` : `edri-evidence-snapshot-${snapshotId}-ALL`;

    // README
    zip.file(`${folder}/README.txt`, [
      'EPOCH DCAA Readiness Index — Evidence Packet',
      `Snapshot ID: ${snapshotId}`,
      `Domain Filter: ${domainKey ?? 'ALL_DOMAINS'}`,
      `Generated At: ${new Date().toISOString()}`,
      `Composite Score: ${snapshot?.compositeScore ?? 'N/A'}`,
      `Scoring Band: ${snapshot?.scoringBand ?? 'N/A'}`,
      '',
      'Files in this packet:',
      '  - manifest.json       Full evidence manifest',
      '  - domain_scores.json  Per-domain raw and weighted scores',
      '  - red_flags.json      Active compliance red flags',
      '  - remediation.json    Remediation queue items',
      '',
      'This packet was generated by the EPOCH DCAA Readiness Index (EDRI).',
      'It should be retained as part of your DCAA pre-audit documentation.',
    ].join('\n'));

    // manifest.json
    const manifest = {
      generatedAt: new Date().toISOString(),
      packetId,
      snapshotId,
      domainKey: domainKey ?? 'ALL_DOMAINS',
      computedAt: snapshot?.computedAt,
      compositeScore: snapshot?.compositeScore,
      scoringBand: snapshot?.scoringBand,
      failureProbability: snapshot?.failureProbability,
    };
    zip.file(`${folder}/manifest.json`, JSON.stringify(manifest, null, 2));

    // domain_scores.json
    const domainScoresData = domainScores.map(d => ({
      domain: d.domainKey,
      rawScore: d.rawScore,
      weight: d.weight,
      weightedContribution: d.weightedContribution,
      gapCount: d.gapCount,
      evidenceCount: d.evidenceCount,
      subScores: d.subScores,
    }));
    zip.file(`${folder}/domain_scores.json`, JSON.stringify(domainScoresData, null, 2));

    // red_flags.json
    const redFlagsData = flags.map(f => ({
      id: f.id,
      flagKey: f.flagKey,
      domain: f.domainKey,
      severity: f.severity,
      title: f.title,
      description: f.description,
      farCitation: f.farCitation,
      potentialScoreRecovery: f.potentialScoreRecovery,
      isActive: f.isActive,
      resolvedAt: f.resolvedAt,
    }));
    zip.file(`${folder}/red_flags.json`, JSON.stringify(redFlagsData, null, 2));

    // remediation.json
    const remediationData = remItems.map(r => ({
      id: r.id,
      domain: r.domainKey,
      title: r.title,
      description: r.description,
      priority: r.priority,
      status: r.status,
      potentialScoreRecovery: r.potentialScoreRecovery,
      assignedTo: r.assignedToDisplayName,
      dueDate: r.dueDate,
      waiverJustification: r.waiverJustification,
    }));
    zip.file(`${folder}/remediation.json`, JSON.stringify(remediationData, null, 2));

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

    // Upload to object storage
    const filename = `${folder}-${Date.now()}.zip`;
    const storagePath = await objectStorage.uploadBuffer(zipBuffer, filename, 'application/zip');

    await db.update(edriEvidencePackets)
      .set({
        status: 'READY',
        completedAt: new Date(),
        storagePath,
        errorMessage: null,
      })
      .where(eq(edriEvidencePackets.id, packetId));
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    await db.update(edriEvidencePackets)
      .set({ status: 'FAILED', errorMessage: message })
      .where(eq(edriEvidencePackets.id, packetId));
  }
}

export async function getEvidencePacketStatus(packetId: number) {
  const packets = await db.select().from(edriEvidencePackets)
    .where(eq(edriEvidencePackets.id, packetId)).limit(1);
  return packets[0] ?? null;
}

export async function streamEvidencePacket(packetId: number, res: import('express').Response): Promise<boolean> {
  const packet = await getEvidencePacketStatus(packetId);
  if (!packet || packet.status !== 'READY' || !packet.storagePath) return false;

  const zipBuffer = await objectStorage.downloadAsBuffer(packet.storagePath);
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="edri-evidence-packet-${packetId}.zip"`);
  res.send(zipBuffer);
  return true;
}
